### ISSUE TITLE
Import by filename is not supported

### ISSUE THREAD

**Issue by dgoldwx2112** [monocongo/climate_indices#103]
Attempting to run the unit tests via Cygwin on Windows 10. I cloned into my Downloads directory with all packages present, changed to the indices_python directory and executed the command to run multiple unit tests. Here was the output:

AzureAD+DavidGold@DESKTOP-94DPDVM /cygdrive/c/Documents and Settings/DavidGold/Downloads/indices_python
$ python -m unittest tests/test_*.py
Traceback (most recent call last):
  File "C:\Users\DavidGold\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\DavidGold\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\DavidGold\Anaconda2\lib\unittest\__main__.py", line 12, in <module>
    main(module=None)
  File "C:\Users\DavidGold\Anaconda2\lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "C:\Users\DavidGold\Anaconda2\lib\unittest\main.py", line 149, in parseArgs
    self.createTests()
  File "C:\Users\DavidGold\Anaconda2\lib\unittest\main.py", line 158, in createTests
    self.module)
  File "C:\Users\DavidGold\Anaconda2\lib\unittest\loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\DavidGold\Anaconda2\lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: Import by filename is not supported.

Any ideas?

**Comment by monocongo** [comment]
Thanks for your input, David.

I do have an idea -- this is related to out-of-date documentation which lists a previous testing command (being addressed in issue #86). The proper command to use is `python setup.py test`

In summary here are the steps you should take if starting from scratch:

`$ git clone https://github.com/monocongo/indices_python.git`
`$ cd indices_python`
`$ conda create -n test_env`
`$ source activate test_env`
`$ pip install .`
`$ export NUMBA_DISABLE_JIT=1`
`$ python setup.py test`
`$ unset  NUMBA_DISABLE_JIT`

**Comment by dgoldwx2112** [comment]
Hi James -

Sorry for the delay in replying; I was out of town for a few days. Let me
try your suggestions and see what happens.

David

**Comment by monocongo** [comment]
No worries, David. Sorry to have closed the issue prematurely, please let me know if anything else goes off the rails for you. And please stay tuned, there's a clean up underway (#65) with an accompanying streamline of the documentation.

**Comment by dgoldwx2112** [comment]
No problem James. Thank you for making this wonderful set of capabilities
available open source!

David

**Comment by monocongo** [comment]
Is this still an issue for you, David? I assume not and closing the issue, for now, please comment or open a new issue if anything is still amiss on your end.
