### ISSUE TITLE
Allow specification of calibration period for spi_gamma and spei_gamma

### ISSUE THREAD

**Issue by jamaa** [monocongo/climate_indices#108]
Contrary to `spi_pearson()` and `spei_pearson()`, `spi_gamma()` and `spei_gamma()` do not have method parameters for specifying the calibration period. I presume that the *_gamma methods always use the entire time series for calibration, but am not sure about this. In any case, it makes sense to be able to specify the calibration period, as is the case with the *_pearson methods.

**Comment by monocongo** [comment]
This is available now, please provide feedback once you've managed to try it out. Please let me know if you need any guidance.

**Comment by jamaa** [comment]
Thanks for implementing this. We noticed one small bug: the following line https://github.com/monocongo/climate_indices/blob/c6d20ef4eff6928887adeca167fd7ec0ab8a5620/climate_indices/compute.py#L654 
should be
`logs = np.log(calibration_values)`
After this change, it seems to work as intended.

**Comment by monocongo** [comment]
Beautiful, thanks for catching that. Should I update, or do you want to fix and create a pull request?

**Comment by jamaa** [comment]
We haven't set up a fork or branch yet, so please update it yourself. We can work with pull requests if we have any larger change propositions in the future .

**Comment by monocongo** [comment]
The above-mentioned bug was fixed by #155, closing now but happy to reopen if any further/related issues are discovered.
