### ISSUE TITLE
Installation issue with official release

### ISSUE THREAD

**Issue by s-m-t-c** [monocongo/climate_indices#170]
**Describe the bug**
There's some discrepancies in the documentation surrounding installation.

Using the official release located here:
https://www.drought.gov/drought/python-climate-indices

When following these instructions exactly I produce the following error at the pip install step. I managed to install the package by tinkering with the folder names but then couldn't pass the tests. 
~~~~
Processing /indices_python-master
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/indices_python.egg-info
    writing pip-egg-info/indices_python.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/indices_python.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/indices_python.egg-info/requires.txt
    writing top-level names to pip-egg-info/indices_python.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/indices_python.egg-info/SOURCES.txt'
    error: package directory 'climate_indices' does not exist
~~~~

I managed to install the github master using these steps: https://climate-indices.readthedocs.io/en/latest/

It successfully passed all the tests but the program can't do any of the SPI or SPEI calculations when I use the example_input data. I'll raise this as a separate issue

Thanks in advance!

**Desktop:**
~~~~
Distributor ID:	CentOS
Description:	CentOS release 6.9 (Final)
Release:	6.9
Codename:	Final
~~~~

Extra info:

Trying to use this library to calculate SPEI over Cambodia.

**Comment by monocongo** [comment]
Thanks for pointing this out.

It seems that I've neglected to include the step where you install the package using setuptools via `$ python setup.py install`. This may actually render the `$ pip install .` command as superfluous? (I'm not very adept with packaging, any help here appreciated!)

I will update the documentation to reflect this installation requirement.

**Comment by monocongo** [comment]
Use `$ python setup.py test` for running tests

**Comment by monocongo** [comment]
We now use `pytest` for testing the package.
