### ISSUE TITLE
error when testing the climate_indices in my mac laptop

### ISSUE THREAD

**Issue by Lixia0911** [monocongo/climate_indices#178]
I'm trying to use the climate indices software in my own mac laptop. 

**To Reproduce**
1. Downloaded the cod by "git clone https://github.com/monocongo/climate_indices.git" 
2. Configured the Python environment to Python 3.6 through installing Miniconda3
3. then did the test by doing "export NUMBA_DISABLE_JIT=1", and "python setup.py test"

**Expected behavior**
It is expected the test should pass

**Screenshots**
![error](https://user-images.githubusercontent.com/40567805/45035766-afeaaf00-b052-11e8-9c57-cfb94c4cd729.jpg)

**Desktop (please complete the following information):**
 - macOS High Sierra
 - Version 10.13.6

**Comment by monocongo** [comment]
Possibly related to #170
