### ISSUE TITLE
Units error for cmip data

### ISSUE THREAD

**Issue by mada0007** [monocongo/climate_indices#267]
Hello so I have this error when I try using cmip5 data
(RAWORK) MU00152044X:scripts mada0007$ python process_grid.py --index spi --periodicity monthly --netcdf_precip /Users/mada0007/Desktop/FOR_SPI/GISS-E2-R_historical/1979-2005_hist.nc --var_name_precip pr --output_file_base /Users/mada0007/Desktop/FOR_SPI/GISS-E2-R_historical/GISS-E2-R_historical  --scales 3 6  --calibration_start_year 1979       --calibration_end_year 2005 
2019-02-19  14:01:04 INFO Start time:    2019-02-19 14:01:04.261052
2019-02-19  14:01:04 INFO Computing 3-month SPI/Pearson
2019-02-19  14:01:04 ERROR Failed to complete
Traceback (most recent call last):
  File "process_grid.py", line 1447, in <module>
    _compute_write_index(kwrgs)
  File "process_grid.py", line 532, in _compute_write_index
    f"Unsupported precipitation units: {dataset[precip_var_name].units}"
ValueError: Unsupported precipitation units: kg m-2 s-1
Traceback (most recent call last):
  File "process_grid.py", line 1447, in <module>
    _compute_write_index(kwrgs)
  File "process_grid.py", line 532, in _compute_write_index
    f"Unsupported precipitation units: {dataset[precip_var_name].units}"
ValueError: Unsupported precipitation units: kg m-2 s-1

Can I please get help as to how I can overcome this?

Thanks in advance.

**Comment by monocongo** [comment]
The issue here is that the precipitation units are "kg m-2 s-1" and we're expecting millimeters or inches. My assumption is that for SPI and PNP this should not matter, it's only relevant for SPEI and the Palmers.

**Comment by mada0007** [comment]
Okay thanks for the clarification yes i want spi and since I am getting this error, how can i possibly over come this?

**Comment by monocongo** [comment]
This is happening in the [process_grid.py](https://github.com/monocongo/climate_indices/blob/master/scripts/process_grid.py#L523) script. While it's possible to handle this in that spot it might be cleaner to handle this outside of the `_compute_write_index` function, or perhaps to handle all units conversion outside of there? In any event I will somehow make an accommodation for this use case, hopefully in the next day or two, please feel free to ping me again here if you don't see this issue resolved by a merged PR soon. In the meantime, an easy fix for this would be to just change the units attribute in the input precipitation NetCDF to "mm" or "inches", but that's an ugly hack...

**Comment by monocongo** [comment]
@mada0007 I have merged an untested fix for this into the develop branch. Can you please try that to verify that it works as expected now? Also can you please refer me to the download location for the input dataset you're using so I can validate the result on my end as well?

**Comment by mada0007** [comment]
Hello all sorry for taking a while to reply. I downloaded the latest version and it works like charm. I am really greatefull for all the help offered me on this platform.
Regards,
