### ISSUE TITLE
It doesn't effectively handle daily datasets which are not 366 days per year

### ISSUE THREAD

**Issue by lincystar** [monocongo/climate_indices#270]
The conversion functions utils.transform_to_366day and utils.transform_to_gregorian were missed to be included in the recently updated versions of the process_grid.py and process_divisions.py scripts.

**Comment by monocongo** [comment]
The calendar conversion was replaced, converting from Gregorian to 366-day for indices computation, then back to Gregorian for output. Updates have been merged into the develop branch.

**Comment by monocongo** [comment]
@lincystar please try the code from the develop branch, and/or refer me to a link where I can download your daily precipitation dataset in order to validate it myself. Please list any related issues you have here so I can be aware and address. Thanks!

**Comment by go1me** [comment]
I find a bug in this PR. if we use -index all  …… --periodicity monthly and dont in put a pet file, the software will calculate the pet,  there will be a error in _compute_write_index on line 584, because the pet have not the argument of periodicity

**Comment by monocongo** [comment]
Thanks for the heads up @haysengithub!

The highlighted bug seems to be fixed in the latest update to the develop branch.

**Comment by monocongo** [comment]
Resolved by #274
