### ISSUE TITLE
pytest failed

### ISSUE THREAD

**Issue by pratyushags** [monocongo/climate_indices#282]
**Describe the bug**
 https://github.com/monocongo/climate_indices.git
pytest failed

**Screenshots**
![image](https://user-images.githubusercontent.com/48307826/54080610-04c8f400-431a-11e9-9081-fa37505bf305.png)

**Desktop (please complete the following information):**
- windows 7 ultimate

**Comment by monocongo** [comment]
So Windows 7 and Python 2.7, correct?

**Comment by monocongo** [comment]
Please use Python 3, as 2.7 is no longer supported. If you still have issues then please let me know, I feel sure we can straighten you out. In general testing the code should not be necessary, just install using `pip install climate-indices` and you should be golden.
