### ISSUE TITLE
Use proper importing practices in tests, eliminate context hack

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#29]
Test files are currently using a somewhat convoluted mechanism to provide what is essentially absolute imports, and it smells like a bad hack. 

Eliminate the need for context.py in tests/test_*.py files.

**Comment by monocongo** [comment]
This appeared to be working and then again not, so moving back to a flat layout without subdirectories for now, will pick this up later.

One interesting item will be to work out the various settings Eclipse/PyDev makes to the PYTHONPATH, etc. that takes care of things that are necessarily done manually at command line. This may be as simple as setting the PYTHONPATH to use the project's directory and/or adding the package into the local site-packages with setuptools.

Creating branch 'flat' for this issue.

**Comment by synflyn28** [comment]
James,

I've taken a look at your code and I think I can fix this issue. I'll fork your repo and see if I can refactor the tests so that contexts.py is no longer needed.

**Comment by synflyn28** [comment]
James,

I've attempted to fix this issue and it looks like I got a fix working on my end. You can check out Pull request #34 if you have time. Thanks!

**Comment by monocongo** [comment]
Thanks again, Justin. The fixes you added look good for the tests. I've tried to follow this convention for the other scripts in the 'task' directory (the task_*.py scripts ingest and then process the indices of their respective input data types), as well as moving the process_*.py scripts back into a 'process' directory. However when I've tried this on command line in bash on Windows and Linux it's still not working as expected, although I can get it to run in PyDev (again I think that PyDev probably monkeys with the PYTHONPATH etc. to eliminate this issue in some cases).

I'll keep the task/* files in place for now even though not working as expected with absolute imports, I will revisit this probably after mid-January after AMS (or someone else feel free to fix).

**Comment by synflyn28** [comment]
James,

What you would do is move those directories (task/ and process/) underneath the indices_python subdirectory as well. Then the full path imports should work as expected. You can make subpackages in the subdirectory as well and that is what I do in my code.

**Comment by monocongo** [comment]
OK so everything should work as I was expected it to before, except that you add one directory layer above *everything*. Seems reasonable, now that it's been explained. Not sure why this has been so tricky for me, I'm used to the Java way of doing things I guess, still transitioning to a Python mindset.  Thanks again for the help/enlightenment.  :)
