### ISSUE TITLE
Continental NaN results with Pearson III distribution for 1- to 3-month SPI

### ISSUE THREAD

**Issue by aleccourt** [monocongo/climate_indices#293]
1- through 3- month Pearson III distribution SPI (and possibly SPEI) results produce incorrect NaN values (either smallest possible value or NaN depending on the season - fall/winter & spring/summer respectively) over higher latitude, Northern Hemisphere, continental locations. 

This issue was introduced with the utilization of the lmoments3 module to fit the data to Pearson II distribution. 

To reproduce:
1.  Used CMORPH global precip. data (0.25 degree, monthly)
2.  Calculate SPI 1- through 3-month

Machine:
- linux server

**Comment by monocongo** [comment]
Thanks, @aleccourt!

I will attempt to reproduce with the [example daily CMORPH daily precipitation input dataset](https://github.com/monocongo/example_climate_indices/blob/master/example/input/cmorph_lowres_daily_conus_prcp.nc), but in the meantime, if you can provide access to the monthly CMORPH dataset you reference above that might be useful.

It's interesting that this only happens at the lower scale values. To confirm: this doesn't happen when computing 6-month or 9-month scales, for example?

I will cook up a version that uses the old code for L-moments that I translated from Fortran into Python to see if that gives better results than the current code which leverages the [lmoments3 ](https://pypi.org/project/lmoments3/) package.

**Comment by monocongo** [comment]
After further investigation, this appears to be related to the nature of the input data and not an issue in the Pearson fitting code per se (i.e. we get the same results with an older version without lmoments3). Nevertheless, it would be good to work out exactly what's going on here in order to better handle edge cases like this.
