### ISSUE TITLE
A bug in SPI  calculation

### ISSUE THREAD

**Issue by pankajkarman** [monocongo/climate_indices#310]
There is probabily a bug in compute.py at line number 442. As length will always be integer, the probability will result in zero if the nominator is less than denominator which will always be the case, causing spi values to be -Inf at those points where rainfall is zero and it can be corrected by multiplying 1.0 to nominator, also line 445 will not be required once this bug is corrected.

**Comment by monocongo** [comment]
Thanks, @pankajkarman . I'm not sure I follow your explanation. Can you please post an example where the bug manifests itself? I appreciate your help.

**Comment by pankajkarman** [comment]
Ok. I'll try to explain with an example code I have created using apart of your library.
![spi 0](https://user-images.githubusercontent.com/34066356/57335878-a2d21280-7141-11e9-8bf8-0eae8eb87e8e.png)
Here in this example, function compute has a line where p is calculated the way it has been calculated in compute.py and it results in -inf at 1987-02-28.
![spi 1](https://user-images.githubusercontent.com/34066356/57336016-17a54c80-7142-11e9-8371-550852093f7a.png)
Now in this example, p is calculated by multiplying 1.0 to the previous value thus converting the same to float and it doesn't give -inf at 1987-02-28 now.

**Comment by monocongo** [comment]
I apologize, I'm still missing your point. Can you please provide an input dataset that causes the error when it's used as input to the `compute.transform_fitted_gamma` function? For example the Excel file you've used as input in your above example. I can then use that as an input to this code and see what's happening with the intermediate values in a debugger.

While you may have an issue with a derivative code you've created based upon the code from this repository I'm not yet convinced that the same issue is present in the original (although I'm happy to be convinced otherwise, so we can eliminate a bug that's gone undetected until now).

**Comment by pankajkarman** [comment]
![spi 2](https://user-images.githubusercontent.com/34066356/57347642-9dd88780-7170-11e9-852c-2e3937673dfb.png)
This is the original code I used for spi calculation with climate_indices and you can see I get NaNs at 1986-01-31 to 1986-03-31.
![spi 5](https://user-images.githubusercontent.com/34066356/57347722-ec862180-7170-11e9-97b0-8d3ee8b31389.png)
 That's because line 432 replaces any zero value with NaN while the treatment for zero values is already there in the below code.
![spi 4](https://user-images.githubusercontent.com/34066356/57347791-30792680-7171-11e9-8478-be05b87a25a0.png)
which is following the below equation:
![spi 3](https://user-images.githubusercontent.com/34066356/57347819-4555ba00-7171-11e9-94a1-5e99192fc557.png)
However, probability of zero will always be zero coz of the issue I raised.
[Monthly_Seasonal_Data_Corrected_Version.xlsx](https://github.com/monocongo/climate_indices/files/3155395/Monthly_Seasonal_Data_Corrected_Version.xlsx)
I used above dataset for spi calculations.

**Comment by pankajkarman** [comment]
I have tried printing the probability of zeros and this is correct as python3 gives float even after integer division, so this NaN problem is coming from somewhere else. By the way, the code I have written doesn't produce NaNs at all. As the problem is not because of the issue I raised, so I would like to close it if you agree.

**Comment by monocongo** [comment]
Thanks for the follow up, @pankajkarman.

I would like to use your Excel dataset as an example input within the [example_climate_indices](https://github.com/monocongo/example_climate_indices) package, as well as creating a Jupyter notebook to demonstrate how this kind of data can be used as input to the `climate_indices` package. Can you please respond with any further information about this dataset? Also I would like to provide attribution to you for the contribution, so if you are interested in that then please forward your name, institution, etc.

I appreciate your participation.
