### ISSUE TITLE
skew variable not assigned in _estimate_pearson3_parameters for `t3 <= 1e-6`

### ISSUE THREAD

**Issue by dougrichardson** [monocongo/climate_indices#329]
When computing the SPI fit with the Pearson III distribution, the function ` _estimate_pearson3_parameters` does not assign a value to the variable `skew` if `t3 <= 1e-6` (line 83 of lmoments.py).

This returns the error `UnboundLocalError: local variable 'skew' referenced before assignment`.

Presumably the function should set `skew = 0`, as a comment on Line 84 states "skewness is effectively zero".

It was just chance that I came across this problem - SPI fitting works for a range of different aggregation scales but fails on a particular value for my data set.

Run on Ubuntu 18.04, 31GB RAM

![climate_indices  _estimate_pearson3_parameters error traceback](https://user-images.githubusercontent.com/54010293/62842927-50346380-bcf9-11e9-9bcf-a676e1b45115.png)

**Comment by monocongo** [comment]
Thanks @boro141! I will make the change you've suggested and let's see if that fixes things. Or feel free to submit a PR.

I appreciate your help/contribution, it's users like you who help keep this code solid.

**Comment by monocongo** [comment]
Please pull from the master branch and try again, @boro141, and if the suggested fix doesn't work to solve your issue then please let me know and we'll look into this further. Or if it does fix things please let me know so I can close this issue.

**Comment by dougrichardson** [comment]
Thanks very much @monocongo! I didn't pull from the master branch but simply added the line `skew = 0.0` into the scripts I already had on my machine and everything runs fine.

**Comment by monocongo** [comment]
Resolved by PR #330
