### ISSUE TITLE
ValueError in computing SPI

### ISSUE THREAD

**Issue by ritviksahajpal** [monocongo/climate_indices#344]
Thanks for a great package! I had a query regarding the code:
In __main__.py, you have the foll. code:

 ```
       input_type = keyword_arguments["input_type"]
        if input_type == InputType.grid:
            chunks = {"lat": -1, "lon": -1}
        elif input_type == InputType.divisions:
            chunks = {"division": -1}
        elif input_type == InputType.timeseries:
            chunks = {"time": -1}
        else:
            raise ValueError(f"Invalid 'input_type' keyword argument: {input_type}")
    dataset = xr.open_mfdataset(files, chunks=chunks)
```

However, this means that `chunks =  {"lat": -1, "lon": -1}` in case of a grid and that results in this error:
```
  File "C:\Users\rit\Anaconda3\lib\site-packages\dask\array\core.py", line 1854, in normalize_chunks
    raise ValueError("Empty tuples are not allowed in chunks. Express "
ValueError: Empty tuples are not allowed in chunks. Express zero length dimensions with 0(s) in chunks
```
Shouldn't the default value for chunks be changed to something like:
`chunks = {"lat": 1, "lon": 1}`

**Comment by monocongo** [comment]
Thank you for your comments, @ritviksahajpal. To be honest I don't remember why we used - 1 for those chunk sizes, although I think it may have been a way to allow xarray make the determination as to the optimal chunk sizes, or perhaps to disable chunking altogether?
