### ISSUE TITLE
Broadcast shape error

### ISSUE THREAD

**Issue by aidenrobert** [monocongo/climate_indices#345]
Hello! I am working on using the climate_indices tool to calculate global SPI values. The input data is ERA-Interim, and I've changed units, variable names and variable order in order for climate_indices to accept them. Now that it does, I have gotten this error:

`Traceback (most recent call last):
  File "/home/x_aidjo/.conda/envs/python3env/bin/process_climate_indices", line 10, in <module>
    sys.exit(main())`
`File "/home/x_aidjo/.conda/envs/python3env/lib/python3.7/site-packages/climate_indices/__main__.py", line 1689, in main
    _compute_write_index(kwrgs)`
  `File "/home/x_aidjo/.conda/envs/python3env/lib/python3.7/site-packages/climate_indices/__main__.py", line 806, in _compute_write_index
    keyword_arguments["data_start_year"])`
  `File "/home/x_aidjo/.conda/envs/python3env/lib/python3.7/site-packages/climate_indices/__main__.py", line 623, in _drop_data_into_shared_arrays_grid
    total_years)`
  `File "/home/x_aidjo/.conda/envs/python3env/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 380, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))`
`ValueError: could not broadcast input array from shape (247) into shape (306)`

The input dataset covers  the full years 1981-2017 (13455 daily values) and I am using a calibration start year of 1981 and calibration end year of 2010. From tracing these back, I see that there is a problem with `total_years` (the line 623 error), `data_start_year` in the output shape (line 806 error), and then this is finally causing the compute_write_index function to fail (the line 1689 error). I cannot understand where 94 and 306 come from, but I am guessing that this is an issue with the time axis — is there a chance you have come across something like this before?

**Comment by monocongo** [comment]
Hi @aidenrobert!

I have not seen anything like this before, at least nothing comes to mind. If you can share your dataset I will try to understand what's happening. You've done a pretty thorough job already -- thanks for your in-depth analysis and careful explanation of the issue at hand.

**Comment by aidenrobert** [comment]
Hej @monocongo, thanks! It's a pretty hefty file, but I read in another thread that you could probably reproduce with lower resolution since the grid size shouldn't matter? If so, I'll try remapping it and reproducing it first and will get back with that to avoid too big of a file.

**Comment by monocongo** [comment]
Yes, that's the way to go. Just trim out a very small grid with all times and run that through the code, and hopefully the issue will appear there as well.

**Comment by aidenrobert** [comment]
Yup, confirmed that it does reproduce the same error. Here you go!

[tp1_box.nc.zip](https://github.com/monocongo/climate_indices/files/3681950/tp1_box.nc.zip)

**Comment by monocongo** [comment]
Hi @aidenrobert I thought I'd ping you to let you know that I've finally had time to look into this, my understanding at this point is that there's an issue around the conversion back and forth between normal (Gregorian) years and 366-day years when using daily data. I hope to have an update that fixes this for you by the end of the year. Stay tuned!

**Comment by monocongo** [comment]
@aidenrobert this appears to actually be an issue with your dataset, which seems to have wonky time values starting around index 4800. Time values are expected to be sequential but the time values in this dataset are jumping around and appear to repeat in places at that part of the time coordinate variable.  For example, try this and tell me if it looks off to you as well:
```
import xarray as xr
ds = xr.open_dataset('/home/james/Downloads/tp1_box.nc')
print(f"{ds_precip.time[4850:5000]}")
```
My results for the above look like this:
```
Time: <xarray.DataArray 'time' (time: 150)>
array(['1995-04-12T06:00:00.000000000', '1995-04-13T06:00:00.000000000',
       '1995-04-14T06:00:00.000000000', '1995-04-15T06:00:00.000000000',
       '1995-04-16T06:00:00.000000000', '1995-04-17T06:00:00.000000000',
       '1995-04-18T06:00:00.000000000', '1995-04-19T06:00:00.000000000',
       '1995-04-20T06:00:00.000000000', '1995-04-21T06:00:00.000000000',
       '1995-04-22T06:00:00.000000000', '1995-04-23T06:00:00.000000000',
       '1995-04-24T06:00:00.000000000', '1995-04-25T06:00:00.000000000',
       '1995-04-26T06:00:00.000000000', '1995-04-27T06:00:00.000000000',
       '1995-04-28T06:00:00.000000000', '1995-04-29T06:00:00.000000000',
       '1995-04-30T06:00:00.000000000', '1995-05-01T06:00:00.000000000',
       '1995-05-02T06:00:00.000000000', '1995-05-03T06:00:00.000000000',
       '1995-05-04T06:00:00.000000000', '1995-05-05T06:00:00.000000000',
       '1995-05-06T06:00:00.000000000', '1995-05-07T06:00:00.000000000',
       '1995-05-08T06:00:00.000000000', '1995-05-09T06:00:00.000000000',
       '1995-05-10T06:00:00.000000000', '1995-05-11T06:00:00.000000000',
       '1995-05-12T06:00:00.000000000', '1995-05-13T06:00:00.000000000',
       '1995-05-14T06:00:00.000000000', '1995-05-15T06:00:00.000000000',
       '1995-05-16T06:00:00.000000000', '1995-05-17T06:00:00.000000000',
       '1995-05-18T06:00:00.000000000', '1995-05-19T06:00:00.000000000',
       '1995-05-20T06:00:00.000000000', '1995-05-21T06:00:00.000000000',
       '1995-05-22T06:00:00.000000000', '1995-05-23T06:00:00.000000000',
       '1995-05-24T06:00:00.000000000', '1995-05-25T06:00:00.000000000',
       '1995-05-26T06:00:00.000000000', '1995-05-27T06:00:00.000000000',
       '1995-05-28T06:00:00.000000000', '1995-05-29T06:00:00.000000000',
       '1995-05-30T06:00:00.000000000', '1995-05-31T06:00:00.000000000',
       '1995-06-01T12:00:00.000000000', '1995-06-02T00:00:00.000000000',
       '1995-05-31T12:00:00.000000000', '1995-06-01T00:00:00.000000000',
       '1995-05-30T12:00:00.000000000', '1995-05-31T00:00:00.000000000',
       '1995-05-29T12:00:00.000000000', '1995-05-30T00:00:00.000000000',
       '1995-05-28T12:00:00.000000000', '1995-05-29T00:00:00.000000000',
       '1995-05-27T12:00:00.000000000', '1995-05-28T00:00:00.000000000',
       '1995-05-26T12:00:00.000000000', '1995-05-27T00:00:00.000000000',
       '1995-05-25T12:00:00.000000000', '1995-05-26T00:00:00.000000000',
       '1995-05-24T12:00:00.000000000', '1995-05-25T00:00:00.000000000',
       '1995-05-23T12:00:00.000000000', '1995-05-24T00:00:00.000000000',
       '1995-05-22T12:00:00.000000000', '1995-05-23T00:00:00.000000000',
       '1995-05-21T12:00:00.000000000', '1995-05-22T00:00:00.000000000',
       '1995-05-20T12:00:00.000000000', '1995-05-21T00:00:00.000000000',
       '1995-05-19T12:00:00.000000000', '1995-05-20T00:00:00.000000000',
       '1995-05-18T12:00:00.000000000', '1995-05-19T00:00:00.000000000',
       '1995-05-17T12:00:00.000000000', '1995-05-18T00:00:00.000000000',
       '1995-05-16T12:00:00.000000000', '1995-05-17T00:00:00.000000000',
       '1995-05-15T12:00:00.000000000', '1995-05-16T00:00:00.000000000',
       '1995-05-14T12:00:00.000000000', '1995-05-15T00:00:00.000000000',
       '1995-05-13T12:00:00.000000000', '1995-05-14T00:00:00.000000000',
       '1995-05-12T12:00:00.000000000', '1995-05-13T00:00:00.000000000',
       '1995-05-11T12:00:00.000000000', '1995-05-12T00:00:00.000000000',
       '1995-05-10T12:00:00.000000000', '1995-05-11T00:00:00.000000000',
       '1995-05-09T12:00:00.000000000', '1995-05-10T00:00:00.000000000',
       '1995-05-08T12:00:00.000000000', '1995-05-09T00:00:00.000000000',
       '1995-05-07T12:00:00.000000000', '1995-05-08T00:00:00.000000000',
       '1995-05-06T12:00:00.000000000', '1995-05-07T00:00:00.000000000',
       '1995-05-05T12:00:00.000000000', '1995-05-06T00:00:00.000000000',
       '1995-05-04T12:00:00.000000000', '1995-05-05T00:00:00.000000000',
       '1995-05-03T12:00:00.000000000', '1995-05-04T00:00:00.000000000',
       '1995-05-02T12:00:00.000000000', '1995-05-03T00:00:00.000000000',
       '1995-05-01T12:00:00.000000000', '1995-05-02T00:00:00.000000000',
       '1995-04-30T12:00:00.000000000', '1995-05-01T00:00:00.000000000',
       '1995-04-29T12:00:00.000000000', '1995-04-30T00:00:00.000000000',
       '1995-04-28T12:00:00.000000000', '1995-04-29T00:00:00.000000000',
       '1995-04-27T12:00:00.000000000', '1995-04-28T00:00:00.000000000',
       '1995-04-26T12:00:00.000000000', '1995-04-27T00:00:00.000000000',
       '1995-04-25T12:00:00.000000000', '1995-04-26T00:00:00.000000000',
       '1995-04-24T12:00:00.000000000', '1995-04-25T00:00:00.000000000',
       '1995-04-23T12:00:00.000000000', '1995-04-24T00:00:00.000000000',
       '1995-04-22T12:00:00.000000000', '1995-04-23T00:00:00.000000000',
       '1995-04-21T12:00:00.000000000', '1995-04-22T00:00:00.000000000',
       '1995-04-20T12:00:00.000000000', '1995-04-21T00:00:00.000000000',
       '1995-04-19T12:00:00.000000000', '1995-04-20T00:00:00.000000000',
       '1995-04-18T12:00:00.000000000', '1995-04-19T00:00:00.000000000',
       '1995-04-17T12:00:00.000000000', '1995-04-18T00:00:00.000000000',
       '1995-04-16T12:00:00.000000000', '1995-04-17T00:00:00.000000000',
       '1995-04-15T12:00:00.000000000', '1995-04-16T00:00:00.000000000',
       '1995-04-14T12:00:00.000000000', '1995-04-15T00:00:00.000000000',
       '1995-04-13T12:00:00.000000000', '1995-04-14T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1995-04-12T06:00:00 ... 1995-04-14
Attributes:
    standard_name:  time
    long_name:      time
    bounds:         time_bnds
    axis:           T
```
My take at this point is that there is no error in this package's code, per se, but instead with the dataset you've used as input. Please correct me if I'm wrong... (it happens all the time!)

**Comment by aidenrobert** [comment]
Nope, you are right! That was a fault that happened through CDO. Thanks very much for the help!
