### ISSUE TITLE
Climate indices--I am following the steps in NASA Webinar Applications of GPM IMERG1 Reanalysis for Assessing Extreme Dry and Wet Periods. After your instructions, it works, but I am facing problem with unit mm/hr , even I have downloaded form data portal monthly data

### ISSUE THREAD

**Issue by Shehabcad** [monocongo/climate_indices#363]
**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: \[e.g. iOS]
- Version: \[e.g. 22]

**Additional context**

**Comment by Shehabcad** [comment]
![Capture](https://user-images.githubusercontent.com/42914908/74109374-1991b580-4b83-11ea-9dd4-27683dde8641.JPG)

**Comment by monocongo** [comment]
Input data is in an incompatible format. It appears to be hourly precipitation data based on the units. Please try again with input data that is daily or monthly.

**Comment by monocongo** [comment]
If you think the data file is corrupt, i.e. using the wrong units, then you can alter the units for the variable using [NCO](http://nco.sourceforge.net/). Once you've done that then try again to see if that fixes things. I suggest renaming the units to "mm".

**Comment by Shehabcad** [comment]
I have downloaded from GES DISC NASA, 
![Capture2](https://user-images.githubusercontent.com/42914908/74109495-2ebb1400-4b84-11ea-8e11-5ef7ca8b8af1.JPG)
when I open it with PanoplyWin  the unit mm/hr

**Comment by monocongo** [comment]
Then please follow my suggestion above, I'm not sure what else to tell you.

**Comment by Shehabcad** [comment]
I tried  to edit the attribute with "ncatted -a Units,precipitation,mode,c,mm/hr "mm " IMERG_concat.nc4"
![Capture](https://user-images.githubusercontent.com/42914908/74147641-f22efd00-4c03-11ea-8d9c-39c8041d1210.JPG)

but I got  the following error

**Comment by monocongo** [comment]
@Shehabcad This is an issue with your installation of NCO, you need to take it up with them. I have had good luck with installing NCO via conda as they describe in their installation documentation, maybe you should give that a try.

Please post a link for the dataset in question. I will try to do this myself to see if the SPI can be computed after the units issue has been resolved.

Also, I recommend contacting the group that curates this dataset to alert them of the invalid precipitation unit, if this is indeed the issue. At least it seems to be, as I assume that monthly precipitation should be measured in millimeters and not millimeters per hour.

**Comment by Shehabcad** [comment]
this the code to edit
ncatted -a units,precipitation,modify,c,mm/hr 'mm' IMERG_concat_ncpdq.nc4
the code for SPI
process_climate_indices --index spi --periodicity daily --netcdf_precip 
../climate_indices/IMERG_concat_ncpdq.nc4 --var_name_precip precipitation --output_file_base ../climate_indices/results/IMERG --scales 3 --calibration_start_year 2000 --calibration_end_year 2019 --multiprocessing all
DATA FILE
https://drive.google.com/open?id=1Zq91iMhWvLG4aQgzAxXmKzvIX-G6EZcv

**Comment by monocongo** [comment]
The command used for the modification of the units attribute name needs to instead be this:
```
$ ncatted -a units,precipitation,modify,c,'mm' IMERG_concat_ncpdq.nc4 fixed.nc
```
Once this has completed the dataset can be used as input to this package for computing SPI:
```
$ process_climate_indices --index spi --periodicity monthly --netcdf_precip fixed.nc --var_name_precip precipitation --output_file_base fixed --scales 6 12 --calibration_start_year 2000 --calibration_end_year 2016 --multiprocessing all 
```
You can then use the resulting SPI datasets for maps. For example, this rendering produced from Panoply:
![fixed_spi_gamma_06_200012](https://user-images.githubusercontent.com/1328158/74248291-5eb60480-4cb5-11ea-9d81-798fe3f0f54e.png)

BTW the current version on PyPI has a bug (see issue #364), please wait until I resolve that before trying again.

Let me know if I can assist further. Good luck!

**Comment by monocongo** [comment]
A new version 1.0.9 is now available on [PyPI](https://pypi.org/project/climate-indices/), please use that or the version from the master branch. Any further issues place let me know.

**Comment by Shehabcad** [comment]
Thank you very much I appreciate your help. It works now, I also   sent the link of this discussion to  NASA ARST

**Comment by bennyistanto** [comment]
Hi I also experience the same error, unsupported precipitation unit. And solved by following @monocongo suggestion to modif the unit to "mm".

I am thinking on, the data is monthly rainfall with unit is mm/hr. It means to get the mm/month we need to multiply it with 672 or 696 or 720 or 744 depend on which month the data is before doing the SPI calculation, is that right?

If we just replacing the mm/hr with mm to make the calculation works, it means we use 'monthly rainfall' data which actually hourly rainfall to calculate SPI1 to SPI24? is it acceptable?

<img width="1920" alt="Screen Shot 2020-07-02 at 4 20 55 PM" src="https://user-images.githubusercontent.com/722584/86341146-1ad19500-bc80-11ea-9520-55f8ca986d04.png">
