### ISSUE TITLE
To which period does the calculated SPI refer to?

### ISSUE THREAD

**Issue by greenfrog203** [monocongo/climate_indices#375]
Hi James,

just to make sure I am right:
I opened the provided example netCDF-Files in ArcMap. (I use the Tool "Make NetCDF Raster Layer".)
I can choose monthly values. For example, if I choose 01/07/2010 at SPI at 6-month scale, I assume the SPI for 01/07/2010 is calculated by the prcp-data from the last six months, thus from 01/Jan/2010 to 01/July/2010 - is this correct? If not, please correct. 
Hope I was able to point out what my question is.
Thanks again in advance!

Green Frog

**Comment by monocongo** [comment]
Yes, this is correct. Or almost, as the value for July 2010 will be computed using the six previous months, including July, so Feb 2010 - July 2010. For example, if you choose to compute 3-month scale then the first two months will not have a value, as the first available month for a computed value will be the third month. I hope this helps!
