### ISSUE TITLE
The missing SPI caused by the zero value of the cumulative precipitation

### ISSUE THREAD

**Issue by Seven-milk** [monocongo/climate_indices#377]
Hi, Jim:
I found that there are some missing value when I use the package to calculate daily SPI, and it is caused by the code in compute.py line 720 "values[values == 0] = np.NaN". Thus, the zeros value correspond to the NaN value of gamma_probabilities. So I add a code in line 735 "gamma_probabilities[np.isnan(gamma_probabilities)] = 0"  to set the NaN gamma_probabilities to zero value. After that, I add "values[:scale-1] = np.NaN" in line 180 of indices.py to make sure the initial (scale - 1) elements could be NaN.

**Comment by monocongo** [comment]
Thanks for this @Seven-milk 

If you can please submit a PR and if possible please include a map showing the differences, i.e. how this change will give valid, non-missing index values. This will help me make a case to the scientists who vet the code (I'm not exactly qualified for that, I just cover the software engineering side of things).

I really appreciate your assistance and attention to this, very helpful.

**Comment by Seven-milk** [comment]
I did a example in [SPI_ISSURE.xlsx](https://github.com/Seven-milk/hello-world/blob/master/SPI_ISSURE.xlsx), and the code in [calculate `SPI](https://github.com/Seven-milk/hello-world/blob/master/calculate%20SPI).
Thanks.

**Comment by monocongo** [comment]
Thanks @Seven-milk, this looks good/reasonable. If you can please submit a PR, I would like to run the code on other datasets with extended zeros and look at the resulting maps and data arrays. Nice job.

**Comment by Seven-milk** [comment]
Sorry Jim, I am trying to submit the PR but there is a check problem, can you see the pull request? If not, I will try anagin.
Thanks.

**Comment by monocongo** [comment]
Yes, sorry for my delayed response, the issue has to do with the tests, in that they are expecting to compute values based on the previous method without these changes, but these changes also require a change to the test(s) since these changes will by definition change the computed values, which will not match with the test fixture values. I'm still not sure what to do yet for this as I have not had feedback from the scientists who can weigh in on this to validate that this is a reasonable change to the method of computation.

**Comment by Seven-milk** [comment]
Thanks Jim, I will wait for this feedback. And there are some information might be useful to describe the problem again:

1. In gamma distribution, the probabily of zero value is not defined;
2. Thus, the probabily of zero value can be defined as "the the number of zeros divided by the total number";
3. During the process of calculation, the values equal to zero is defined as np.NaN for fitting gamma;
4. I added a line to transform these NaN to "the the number of zeros divided by the total number" for avoiding missing SPI, which caused by these NaN.

**Comment by monocongo** [comment]
Thanks @Seven-milk this is helpful. Again thanks for your work on this, it's appreciated.
