### ISSUE TITLE
Format of NetCDF mismatch

### ISSUE THREAD

**Issue by vuminhtue** [monocongo/climate_indices#386]
Hi authors,
I know this should be simple fix but Im sure that other researchers also have same issue.
The error that I got is: "ERROR Invalid dimensions of the precipitation variable: ('time', 'lat', 'lon'), (expected names and order: ('lat', 'lon', 'time'))"

I know this is due to the format of my own NetCDF file and the way to resolve this problem to my understanding is to reread and rewrite the NetCDF file to match with your input example.
However, I would like to check if your python code is able to read the other format for example ('time', 'lat', 'lon') without having to modify the NetCDF?

Thanks in advance

**Comment by monocongo** [comment]
Thanks @vuminhtue 

This is happening in the main processing script code [here](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/__main__.py#L79).

This *should* be handled by the `_prepare_file` function but maybe it's being skipped in your case?

There is a pretty strict expectation as to what dimensions will be present and what they'll be named, which is, more or less, some combination of time/lat/lon for gridded datasets.

If you can provide an example NetCDF file then I can step through the code to see what's going wrong for your use case.

**Comment by vuminhtue** [comment]
Thanks for your answer. Please take a look at the file here:
https://www.dropbox.com/s/jahow78ldibb1ua/sample.nc?dl=0

This is actually your file: nclimgrid_lowres_prcp.nc that has been reread and rewrite using convsh.
You can just try using the spi command.

python scripts/process_grid.py --index spi --periodicity monthly --netcdf_precip sample.nc --var_name_precip  prcp --output_file_base sample_out --scales 6 12 --calibration_start_year 1951 --calibration_end_year 2010

**Comment by vuminhtue** [comment]
![image](https://user-images.githubusercontent.com/43855029/78592189-b3d44980-7812-11ea-823a-f1973f929c60.png)

**Comment by monocongo** [comment]
I see your problem, I think, or at least something unusual: you are using `scripts/process_grid.py` but that script is deprecated and is replaced by `src/__main__.py` and the corresponding entry point controller script [`process_climate_indices`](https://github.com/monocongo/climate_indices/blob/master/setup.py#L57).

Can you please try again using that entry point, as described in the latest documentation? You should clone this repository in order to get the latest, up-to-date code. The version at drought.gov is quite out-of-date, they should be pointing to this repository now instead I think.

**Comment by vuminhtue** [comment]
Thanks so much. It ran flawlessly.
It may benefit other, following are the steps I've done:
- Create conda environment
- pip install climate-indices
- git clone https://github.com/monocongo/climate_indices.git
- cd climate_indices
- python setup.py install
the binary process_climate_indices can be found in my conda env bin.

**Comment by vuminhtue** [comment]
The coolest thing is that it can utilize multiple cores in my machines (40 cores).
You can close this ticket.
Thanks again

**Comment by monocongo** [comment]
I'm glad things are working for you now. Please feel free to post issues here or contact me via email if I can help in the future. This is a side project for me now but I like to keep it useful so bugs/issues are always of interest. Thanks for your participation/contributions, @vuminhtue !
