### ISSUE TITLE
nco.NCOException error

### ISSUE THREAD

**Issue by AnnMt** [monocongo/climate_indices#390]
Hello, I'm trying to calculate the SPEI index, firstly I'm calculating PET by using a nc file I created with python.

I'm using the example provided in the documentation, and this is what I run in the terminal:
`
process_climate_indices --index pet --periodicity monthly --netcdf_temp F:\SMN\Datos\Interpolaciones\TEMP\TMEAN_Interp_1950_2019.nc --var_name_temp Monthly_TMEAN --output_file_base F:\SMN\PET_monthly --multiprocessing all_but_one`

However, I get the following error (since I'm new with this I'm adding the screenshot of the whole console in case is helpful):

![imagen](https://user-images.githubusercontent.com/63747181/79380796-8f6d2100-7f26-11ea-8fb1-e0e82d938550.png)

I'm guessing there is something odd with the nc file but I'm not sure of how to fix it, here's the  [link]( https://www.dropbox.com/s/lrdxyyej4v5zvwd/TMEAN_Interp_1950_2019.zip?dl=0) from where you can download it.

Thanks.

**Comment by monocongo** [comment]
When I tried with this dataset I encountered an unsupported units error:
```
Traceback (most recent call last):
  File "/home/james/git/climate_indices/src/climate_indices/__main__.py", line 1713, in main
    kwargs
  File "/home/james/git/climate_indices/src/climate_indices/__main__.py", line 781, in _compute_write_index
    raise ValueError(f"Unsupported temperature units: {temp_unit}")
ValueError: Unsupported temperature units: degrees
Traceback (most recent call last):
  File "/home/james/miniconda3/envs/climate/bin/process_climate_indices", line 11, in <module>
    load_entry_point('climate-indices', 'console_scripts', 'process_climate_indices')()
  File "/home/james/git/climate_indices/src/climate_indices/__main__.py", line 1713, in main
    kwargs
  File "/home/james/git/climate_indices/src/climate_indices/__main__.py", line 781, in _compute_write_index
    raise ValueError(f"Unsupported temperature units: {temp_unit}")
ValueError: Unsupported temperature units: degrees
```

I then modified the values to `degrees_fahrenheit` using NCO:
```
$ ncatted -a units,Monthly_TMEAN,m,c,degrees_fahrenheit -h -O ~/data/test/TMEAN_Interp_1950_2019.nc 
```
I was then able to complete the computation:
```
$ process_climate_indices --index pet --periodicity monthly --netcdf_temp ~/data/test/TMEAN_Interp_1950_2019.nc --var_name_temp Monthly_TMEAN --output_file_base ~/data/test/PET_monthly --multiprocessing all_but_one
2020-04-20  23:27:13 INFO Start time:    2020-04-20 23:27:13.315025
2020-04-20  23:27:20 INFO Computing PET
2020-04-20  23:29:27 INFO End time:      2020-04-20 23:29:27.943163
2020-04-20  23:29:27 INFO Elapsed time:  0:02:14.628138
```
![pet_thornthwaite in PET_monthly_pet_thornthwaite](https://user-images.githubusercontent.com/1328158/79823781-88994080-8362-11ea-840b-03344c843961.png)

¡Viva México!


BTW you are not the first to report unusual behavior when running on WIndows, see issue #387. This appears to be a different problem, it seems that the issue you were having was an access denial, perhaps because of permission issues?

**Comment by AnnMt** [comment]
Hello! Thank you for your response!

I actually found out that there was a problem with my nco and changing the (lat,lon,time) location. My file had this shape: (time,lat,lon) and when nco tried to change it to (lat,lon,time) it couldn't do it, I still don't know why maybe there is something with that acces denial, so I swaped the dimensions on python before using the script and then I also got the units problem, fixed it and then everything work out fine 😄 

This climate_indices tool is extremely helpful! 

Muchísimas gracias!

**Comment by monocongo** [comment]
OK, so it seems that you are the second person to recently have trouble with the reordering of dimensions when running the code on Windows. I wonder if this is an issue with NCO or perhaps with the Python bindings ([pynco](https://github.com/nco/pynco)). This issue may be related to [this one](https://github.com/nco/pynco/issues/48). I guess the best way to find out is to find a Windows machine and run a small script that performs reordering of dimensions with NCO as we do in this code ([here](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/__main__.py#L1533)), to see if it fails in the same way.

Gracias por usar este paquete de software, avíseme si puedo ayudarlo nuevamente.

**Comment by AnnMt** [comment]
Hello again!

I am now able to run the program without problem, however I've realized a
problem when you have a value of 0 in precipitation data. A friend and I
managed to fix it, and we
wanted to let you know, but we saw that this problem was already addressed,
so we wanted to know if you want some examples on how it used to fail and
how now it is fixed, or you
already have this on your mind.

Let me know if we can help you, again thank you for this package, it's been
quite useful.

Saludos :)

**Comment by monocongo** [comment]
Yes, other users have had this come up before I think, and it's possible we have a good fix in place in this [PR](https://github.com/monocongo/climate_indices/pull/384). I am hesitant to merge the PR however since it is a significant update and I don't feel qualified to vet it from a scientific perspective (I'm not a scientist, only responsible for the programming). So if that PR appears to solve your problem and/or you can also submit a PR to show how you solved your issue then it may be helpful. Gracias, compa!

**Comment by AnnMt** [comment]
Thank you!

We solved in a similar way in the compute.py file with

    if np.isnan(gamma_probabilities).any():
       gamma_probabilities[np.isnan(gamma_probabilities)] = 0

If it helps to someone we may submit de PR so you can check it out.


Gracias a ti compita! :)

**Comment by AnnMt** [comment]
Hello again!

Well, we've been using this library and it has worked pretty well! I'm
writing because soon the North American Drought Monitor 2020 Forum will
take place, and
we want to show some results using this library, I was wondering if you
would like a certain type of citation or the one that appears on the page
is ok?


Muchísimas gracias por todo! :D

**Comment by monocongo** [comment]
Yes, thanks a lot, @AnnMt !

Much of the work in this package was funded by NIDIS, so if you can contact Steve Ansari, Mike Brewer, Deke Arndt, and/or Richard Heim (all from NOAA and probably in attendance at the Drought Forum) to let them know that you are using this package then it will be appreciated. Those are the scientists who had the most input as to the scientific integrity of this package (I just program it, I'm not a scientist).

Thanks again for letting me know about this, as I'm always happy to know that the package is being used and is helpful. Gracias y saludos!

**Comment by AnnMt** [comment]
You are right! Mr. Richard Heim will attend! Hope they like what we’ve been obtaining.

Thank you so much for always answering! 

Saludos y cuídense :) 

domingo, 8 de noviembre de 2020 9:06 -0600 de notifications@github.com  <notifications@github.com>:
