### ISSUE TITLE
Error while running "python setup.py test" command on linux as well as Anaconda powershell prompt

### ISSUE THREAD

**Issue by sumi137** [monocongo/climate_indices#392]
![error](https://user-images.githubusercontent.com/64465878/80478797-a9b5ee80-896b-11ea-9b0c-c1e6de011142.jpeg)
**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: \[e.g. iOS]
- Version: \[e.g. 22]

**Additional context**

**Comment by monocongo** [comment]
@sumi137 it appears that you're using an out-of-date version of the code. Can you please try again using the latest code pulled from the master branch of this repository?

Please reference the documentation's [testing](https://climate-indices.readthedocs.io/en/latest/#testing) section.

**Comment by sumi137** [comment]
okay, Thank you so much for your reply, I am looking into it.

**Comment by avitomar12** [comment]
thank @monocongo 
On website previous version is there due to which the problem occur.
https://www.drought.gov/drought/data-maps-tools/software

**Comment by monocongo** [comment]
Thanks @avitomar12 

Yes, I have asked them to no longer use that out-of-date version of the code, I'm not sure why they haven't updated that yet...

BTW I no longer work at NCEI/NOAA so I have no control over this. I recommend you use the code from this repository, as it will always be the most up-to-date.

(Please star this repository if it is useful. Thanks!)

**Comment by sumi137** [comment]
Hello again,
Thanks for the updated version. 
![palmer_error](https://user-images.githubusercontent.com/64465878/80700151-d4827d00-8afa-11ea-9aa4-36b3300d6653.jpeg)
I was trying to run the eaxmple files from here https://github.com/monocongo/example_climate_indices/. SPI, SPEI, PET commands were successful but  I am having trouble with palmer indices (PDSI, scPDSI, PHDI, Z-index, PMDI and PNP), I am getting this error. kindly go through it.

**Comment by monocongo** [comment]
The Palmer indices are included to provide a starting point for others who might want to complete the implementation. I don't know of another open-source Python implementation of PDSI etc. If one exists then we'd like to incorporate it here, as the implementation we have now is very close to matching the current results from NOAA but in some cases, it goes off, and as a result we can't confidently (i.e. shouldn't) use it for proper research since the real experts in the field (not me!) haven't properly vetted/fixed it.
