### ISSUE TITLE
There is a big difference in the comparison of the data

### ISSUE THREAD

**Issue by TreeGuo** [monocongo/climate_indices#393]
Dear professor,
       I ran the program you wrote, I calculated the scpdsi and compared it with the scpdsi data downloaded from the CRU website. I found that there was a big difference with the data, and all the data after I used the calculated data for regional averaging became missing values. But I don't know where the problem is and how to work on it .

**Comment by monocongo** [comment]
Hi @TreeGuo Can you please be more detailed and list what you've done step by step? It has been a long time since I worked on the SCPDSI portion of the code but I will do my best to assist you if possible.

**Comment by TreeGuo** [comment]
Thank you so much for your reply,the script and datas in( https://github.com/TreeGuo/Drought_Index)that I used.The (GLDAS_V2.NOAH025_CRU_SCPDSI.1948_2014.nc) file is output from your program and the other data is input data（prep,pet and awc）.

**Comment by TreeGuo** [comment]
> Hi @TreeGuo Can you please be more detailed and list what you've done step by step? It has been a long time since I worked on the SCPDSI portion of the code but I will do my best to assist you if possible.

I also used R  to calculate SCPDSI before, and the input datas was nc file, but surprisingly, the spatial distribution of the output file was very strange.

**Comment by monocongo** [comment]
Hi @TreeGuo , I have only briefly looked into this and my first question is why have you used a custom script rather than use the command line interface which will manage so much of this for you? If you can use that approach then it may eliminate the question as to whether or not the error is with your code (the build of the result NetCDF, for example, could be a source of error).

For example, use a command like this:

```
$ process_climate_indices --index palmers --periodicity monthly --netcdf_precip E:\disorder\bujidao\Desktop\datas\datas\index_parameters_1948-2014.nc --var_name_precip pre --netcdf_pet E:\disorder\bujidao\Desktop\datas\datas\index_parameters_1948-2014.nc --var_name_pet pet --netcdf_awc E:\disorder\bujidao\Desktop\datas\datas\index_parameters_1948-2014.nc  --var_name_awc awc --output_file_base <out_dir>/nclimgrid_lowres --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all
```
You may need to monkey with the arguments in the command above but this is pretty close to what you should try. I hope this helps!

**Comment by TreeGuo** [comment]
> Hi @TreeGuo , I have only briefly looked into this and my first question is why have you used a custom script rather than use the command line interface which will manage so much of this for you? If you can use that approach then it may eliminate the question as to whether or not the error is with your code (the build of the result NetCDF, for example, could be a source of error).
> 
> For example, use a command like this:
> 
> ```
> $ process_climate_indices --index palmers --periodicity monthly --netcdf_precip E:\disorder\bujidao\Desktop\datas\datas\index_parameters_1948-2014.nc --var_name_precip pre --netcdf_pet E:\disorder\bujidao\Desktop\datas\datas\index_parameters_1948-2014.nc --var_name_pet pet --netcdf_awc E:\disorder\bujidao\Desktop\datas\datas\index_parameters_1948-2014.nc  --var_name_awc awc --output_file_base <out_dir>/nclimgrid_lowres --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all
> ```
> 
> You may need to monkey with the arguments in the command above but this is pretty close to what you should try. I hope this helps!

Thanks to your answer, I've worked out this problem.The codes without complaints.
