### ISSUE TITLE
process_climate_indices command not found 

### ISSUE THREAD

**Issue by crestedcaracaryn** [monocongo/climate_indices#394]
After installing NetCDF Operators 

$ conda install -c conda-forge nco

I tried running the Palmer's Monthly with example data but it says my command "process_climate_indices" cannot be found. I'm running MacOS Catalina - is there something else that needs to be done?

**Comment by lukruh** [comment]
have u installed this package with `pip install climate-indices` while your environment is activated?

**Comment by crestedcaracaryn** [comment]
Yeah, I did that. Here is a screenshot ...

<img width="1678" alt="Screen Shot 2020-07-20 at 9 19 37 PM" src="https://user-images.githubusercontent.com/68565212/88005340-ce36e800-cace-11ea-9ebc-cd458ebf9367.png">

**Comment by lukruh** [comment]
The installation of the package should have added a `process_climate_indices` file in your environment: `/opt/miniconda3/envs/indices_env/bin/`.
Could you check if such a file exists? Do you have installed the library from within this environment the first time, the screenshot only shows that it has been installed already. If you are not sure you can install it again with `pip uninstall climate_indices` `pip install climate_indices`. (A `pip install --upgrade --force-reinstall climate_indices` or `pip install --ignore-installed climate_indices` may work too but I'm not sure..)

**Comment by crestedcaracaryn** [comment]
I was running python 3.8 and changed environment to 3.7 and it worked... not sure why that would have helped but it did

**Comment by monocongo** [comment]
Are you up and running now, @crestedcaracaryn ? Please advise if so, so we can close this issue. I hope all else is working well for you now.

**Comment by crestedcaracaryn** [comment]
@monocongo this issue seems to be resolved but I am not up and running... I can make a new issue report

**Comment by monocongo** [comment]
OK, up to you, hopefully we can resolve your issues.
