### ISSUE TITLE
all tests working except palmers 

### ISSUE THREAD

**Issue by crestedcaracaryn** [monocongo/climate_indices#395]
all tests have run successfully except palmers. Attached are screenshots of the errors when trying to run. Below is the command and initial error... there is also a long list of other exceptions occurred when handling this one. 

(palmers) Caryns-MacBook-Pro:climate_indices-master caryn.ross$ process_climate_indices --index palmers --periodicity monthly --netcdf_precip /Users/caryn.ross/Desktop/climate_indices-master/example_data/input/nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet /Users/caryn.ross/Desktop/climate_indices-master/example_data/input/nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc /Users/caryn.ross/Desktop/climate_indices-master/example_data/input/nclimgrid_lowres_soil.nc  --var_name_awc awc --output_file_base /Users/caryn.ross/Desktop/climate_indices-master/example_data/results/palmers/nclimgrid_lowres --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all

2020-07-23  09:13:58 INFO Start time:    2020-07-23 09:13:58.668712
2020-07-23  09:13:58 INFO Computing PALMERS
2020-07-23  09:14:18 ERROR Failed to complete

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/miniconda3/envs/palmers/lib/python3.7/site-packages/numba/core/errors.py", line 745, in new_error_context
    yield
  File "/opt/miniconda3/envs/palmers/lib/python3.7/site-packages/numba/core/lowering.py", line 273, in lower_block
    self.lower_inst(inst)
  File "/opt/miniconda3/envs/palmers/lib/python3.7/site-packages/numba/core/pylowering.py", line 171, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7fb4ef75e4e0>)

**Comment by crestedcaracaryn** [comment]
<img width="1680" alt="Screen Shot 2020-07-23 at 9 15 57 AM" src="https://user-images.githubusercontent.com/68565212/88297875-153afe00-ccc6-11ea-9d7d-d0f2b205b4e4.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 9 16 26 AM" src="https://user-images.githubusercontent.com/68565212/88297905-1bc97580-ccc6-11ea-9f6b-d3300a4e476c.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 9 16 48 AM" src="https://user-images.githubusercontent.com/68565212/88297910-1ec46600-ccc6-11ea-84a1-caeae898ea8a.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 9 16 52 AM" src="https://user-images.githubusercontent.com/68565212/88297929-2257ed00-ccc6-11ea-8871-52a306dc8839.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 9 17 05 AM" src="https://user-images.githubusercontent.com/68565212/88297942-26840a80-ccc6-11ea-9c12-9c84fc857538.png">

**Comment by monocongo** [comment]
This appears to be related to [numba](http://numba.pydata.org/). Can you please set the [environment variable to ignore numba's just-in-time compilation](https://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_DISABLE_JIT) and try again? I.e. do this:
```
$ export NUMBA_DISABLE_JIT=1
```

**Comment by crestedcaracaryn** [comment]
@monocongo it works! thank you!!

**Comment by monocongo** [comment]
OK, great news! A word of caution, the Palmers are the least scientifically reliable (the jury is still out as far as a comparison evaluation vs. the original NOAA PDSI Fortran code on which our implementation is based) and take the longest to compute. In any event if you have other questions let us know here. Happy indexing!
