### ISSUE TITLE
Issue with netcdf4 when running through Git Bash on Windows 

### ISSUE THREAD

**Issue by crestedcaracaryn** [monocongo/climate_indices#397]
I have previously run this on my mac and it worked - I am now having to run this program on a windows computer. I have downloaded Git Bash, Python, and Miniconda successfully.  Everything seems to be working up until the point of actually running the tests with example data. Here is the code I entered trying to run the palmers test and the following error message.... 

$ process_climate_indices --index palmers --periodicity monthly --netcdf_precip C:\Users\cdross\Desktop\ClimateIndices\example_data\input\nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet C:\Users\cdross\Desktop\ClimateIndices\example_data\input\nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc C:\Users\cdross\Desktop\ClimateIndices\example_data\input\nclimgrid_lowres_soil.nc  --var_name_awc awc --output_file_base C:\Users\cdross\Desktop\ClimateIndices\example_data\results\palmers\nclimgrid_lowres --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all

2020-08-13  16:42:26 INFO Start time:    2020-08-13 16:42:26.681567
2020-08-13  16:42:26 ERROR Failed to complete

Traceback (most recent call last):
  File "c:\users\cdross\miniconda3\envs\palmers\lib\site-packages\xarray\backends\file_manager.py", line 198, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "c:\users\cdross\miniconda3\envs\palmers\lib\site-packages\xarray\backends\lru_cache.py", line 53, in __getitem__
    value = self._cache[key]

KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('C:\\Users\\cdross\\Desktop\\ClimateIndices\\UserscdrossDesktopClimateIndicesexample_datainputnclimgrid_lowres_prcp.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

**Comment by monocongo** [comment]
This appears to be a [bug in xarray](https://github.com/pydata/xarray/issues/2535).

Maybe try rebuilding your Python environment and making sure that all packages installed with conda come from `conda-forge`?
