### ISSUE TITLE
Running Palmers for One Pixel Location 

### ISSUE THREAD

**Issue by crestedcaracaryn** [monocongo/climate_indices#398]
What would be the best way to run Palmers for one location - i.e. one pixel? Is it necessary to use NetCDF files for each of the variables - temp, precip, awc - or is there a way to use a CSV file containing all of the data?

**Comment by monocongo** [comment]
You can use [this function](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/palmer.py#L2199) for a single pixel.

Yes, you can use a CSV or any other approach for storing the data, you just need to somehow get it into numpy arrays. You only need a NetCDF if using the CLI.

**Comment by monocongo** [comment]
Please bear in mind that this Palmer implementation, while faithful to the original NOAA/NCDC Fortran code I started from, is still somewhat experimental, and as such, I'd not recommend it for serious non-academic work. If you use it in your research please let me know how this Palmer implementation stands up to others, it may help with the eventual scientific vetting of this code, something that never completed while I worked on this at NOAA/NCEI). Thanks!
