### ISSUE TITLE
Using CSV as input 

### ISSUE THREAD

**Issue by crestedcaracaryn** [monocongo/climate_indices#399]
When using CSVs as inputs - converted to numpy arrays - is there a specific way it needs to be formatted?

**Comment by monocongo** [comment]
The numpy arrays are representing a time series for a single lat/lon point. The `indices.*` functions take a numpy array 

Assume the data "cube" has dimensions (lat, lon, time). A naive way to loop over the data:
```
input_data_shape = input_data.shape  # this gets the actual (lat, lon, time) tuple
for i in range(input_data_shape[0]):
    for j in range(input_data_shape[1]):
        output_data[i, j] = indices.spi(values=input_data_shape[i, j], scale=...)
```

I hope the above is useful, but let me know if you have further questions.
