### ISSUE TITLE
SPEI calculation, variables contain non-matching latitudes

### ISSUE THREAD

**Issue by bennyistanto** [monocongo/climate_indices#405]
**Describe the bug**
ERROR caused by Precipitation and PET variables contain non-matching latitudes.

**To Reproduce**
1. I used pre-processed (rename variable, dimension and unit) monthly precipitation data 1983-2016 from CHIRPS (I have successfully generate SPI using this data) and monthly PET data generated from CHIRTS temperature. (Reference: https://github.com/monocongo/climate_indices/issues/404#issuecomment-735511962)
2. Used script `$ process_climate_indices --index spei --periodicity monthly ......` as written in the documentation to calculate SPEI monthly

I have manually check the data through ArcGIS and found that PET (CHIRTS temperature grid - red color) do not cover as much as precipitation (blue color) data. How to solve this problem? I sure this is will always happen if we are dealing with various data from different provider.

Should we re-gridding both data, so the coverage is adjusted well? If yes, how to do that?

<img width="1119" alt="Screen Shot 2020-11-30 at 2 34 02 PM" src="https://user-images.githubusercontent.com/722584/100582432-ceb47a80-331b-11eb-8ddf-0c03cc218e71.png">

**Expected behavior**
SPEI calculation completed.

**Screenshots**
1. SPEI error.
   <img width="1028" alt="Screen Shot 2020-11-30 at 2 36 21 PM" src="https://user-images.githubusercontent.com/722584/100582046-361dfa80-331b-11eb-80d7-7a070186bc6f.png">

2. Precip data.
   <img width="938" alt="Screen Shot 2020-11-30 at 2 50 33 PM" src="https://user-images.githubusercontent.com/722584/100582177-6b2a4d00-331b-11eb-9857-6a696d84064f.png">

3. PET data.
   <img width="938" alt="Screen Shot 2020-11-30 at 2 39 29 PM" src="https://user-images.githubusercontent.com/722584/100582218-7ed5b380-331b-11eb-85eb-7574180e0d88.png">

**Desktop (please complete the following information):**
- macOS Big Sur, with Anaconda 4.9.2

**Comment by monocongo** [comment]
Yes, a common grid is required. We require the same lat/lon/time dimensions for the precipitation and PET (or temperature) datasets.

I have had lots of help with this kind of problem in the past from the [NCO help forum](https://sourceforge.net/p/nco/discussion/9830). Sorry I can't help more with that.
