### ISSUE TITLE
available water capacity data

### ISSUE THREAD

**Issue by helena434** [monocongo/climate_indices#417]
Hi,
I want to calculate the Palmer Drought Severity Index for an African region and for that raster data about the available water capacity is a requirement. Unfortunately, the example data provided only covers the U.S.. Are there any suggestions on where I could find aws data compatible with this code, either on a global or African scale?

**Comment by monocongo** [comment]
I apologize, I can't provide a source for AWC datasets for African regions.

I will close this ticket since it does not reference an issue with the software itself. Sorry I can't be of more assistance.

Good luck, @helena434 !

**Comment by samburu** [comment]
@helena434  [ISRIC](https://data.isric.org/geonetwork/srv/eng/catalog.search#/search?facet.q=keyword%2Favailable%20water%20capacity) is a good source of soil data please check it out.

**Comment by monocongo** [comment]
Please bear in mind that the PDSI and the other Palmers herein are expriemental and not fully vetted (in my opinion) so please use with caution! If we could get some attention on that, comparing against other implementations of the various Palmers being used in the wild, it would be very helpful. I'm a programmer not a climate scientist so I don't feel qualified to validate the results of the code, only that the package itself is of reasonably high quality and well-maintained.
