### ISSUE TITLE
_pearson_fit uses a numpy mask that is never true

### ISSUE THREAD

**Issue by cshields143** [monocongo/climate_indices#421]
A line of code in the `_pearson_fit` function attempts to sanitize values in a Numpy array that are either null or very small; but the way it tries to sanitize them is (virtually) guaranteed to never change the array.

```
[line 398] minimums_possible = _minimum_possible(skew, loc, scale)
[line 399] minimums_mask = values <= minimums_possible
...
[line 415] nans_mask = np.isnan(values)
[line 416] values[np.logical_and(minimums_mask, nans_mask)] = 0.0005
```

The way `np.logical_and` works is to only be 1/true if *both* masks are 1/true. But `minimums_mask` is generated with a numerical comparison, meaning that `nan` values will cause it to be false; and `np.isnan`, of course, will only be true if the value is `nan`. The last line above, 416, is akin to saying, "Only change the value to 0.0005 if it both is and is not `nan`"

From context, it is clear that this `np.logical_and` is meant instead to be `np.logical_or`

**Comment by cshields143** [comment]
Very simple fix, just putting a pull request together

**Comment by cshields143** [comment]
I misinterpreted the code! We're intentionally comparing values prior to & posterior to calculating the CDF—it *should* be `and`

**Comment by monocongo** [comment]
While this ended up being a non-issue I still want you to know how much I appreciate the attention to these details. Thanks for the effort, @cshields143 !
