### ISSUE TITLE
Calculate the SPI from an xr.dataset from Python (instead of command line)

### ISSUE THREAD

**Issue by SouhailAB** [monocongo/climate_indices#427]
**Describe the bug**
I used the script below shared in issue #326 but I can not figure out the error that raises.
Following you will find a screenshot of my code, error, and a link to my dataset.

**Screenshots**
![image](https://user-images.githubusercontent.com/69425790/115215718-4deff280-a0f3-11eb-814c-de1b8fcdd429.png)
![image](https://user-images.githubusercontent.com/69425790/115215784-5c3e0e80-a0f3-11eb-8056-08b751f45143.png)
![image](https://user-images.githubusercontent.com/69425790/115215899-7f68be00-a0f3-11eb-881f-b806586a4992.png)
![image](https://user-images.githubusercontent.com/69425790/115215953-8e4f7080-a0f3-11eb-8538-e47841872539.png)
![image](https://user-images.githubusercontent.com/69425790/115216002-98716f00-a0f3-11eb-94de-81493280febc.png)
![image](https://user-images.githubusercontent.com/69425790/115216039-a1fad700-a0f3-11eb-838a-9b2ddb8c762c.png)

**Link to dataset**
https://drive.google.com/file/d/1tT8kYP1bT8YutZZs4vf8zi6DtN86Fd8e/view?usp=sharing

**Desktop (please complete the following information):**
- Windows
- 10

**Additional context**
The script runs fine when the values of the latitude are transposed (i.e from 10.75 to 12.75 degrees), however, these values should be in the correct order (i.e from 12.75 to 10.75 degrees)

**Comment by SouhailAB** [comment]
I get the same issue when computing the PET. It works with  the incorrect order of latitude values

**Comment by monocongo** [comment]
I have run into this before as well. It is a bug/feature of xarray and is not an issue with this package's code, as far as I can tell. I would instead raise this issue in the xarray issue tracker, as someone there who is more familiar with xarray will likely be able to help you. If it's working OK with the latitude values in what you consider to be the wrong order then just reorder the latitude values after it's finished computing the index.

**Comment by SouhailAB** [comment]
It worked just fine! Thank you for the recommendation, I'm closing this issue.
