### ISSUE TITLE
pdsi

### ISSUE THREAD

**Issue by fipoucat** [monocongo/climate_indices#431]
I want to compute pdsi from cmip6 models, have precipitation, temperature and soil moisture and wonder where to get awc or how to compute it in my area Africa?
Any one knows a global awc datasets or a way to get it from cmip6 models?

Hints highly welcome,

Thank you.

**Comment by monocongo** [comment]
Please only use this issue tracker to report issues with the software in this repository. This is not the place to request guidance on where to find datasets. I apologize and wish I could help you more, but this is the wrong forum. Have you not tried asking the CMIP group?

In any event I do not advise to use the PDSI provided in this package as it is not sufficiently vetted for proper scientific usage, but neither are the PDSI codes being used by others, most don't even provide open source code and you just have to trust the scientists that their implementations are solid/reliable, but they're not, and I'm ranting now...

**Comment by fipoucat** [comment]
OK, thak you
