### ISSUE TITLE
Asking question about SPI calculation

### ISSUE THREAD

**Issue by Nazira5** [monocongo/climate_indices#434]
In the calculation of SPI, is it possible to be able to change starting and ending calibration time not from January-December, for example,  start time October previous year and ending September next year?

**Comment by monocongo** [comment]
This is not yet possible, it will be a feature request. When a calibration period is specified it is interpreted as January of the calibration start year through December of the calibration end year, inclusive.

If possible please provide further details about what you'd like to do. Is this something that others would benefit from or is it a niche use case? Is it for monthly or daily observations?

**Comment by Nazira5** [comment]
Thank you very much for your reply. It would be great if you could do it near future, as I would like to compare SPI with other vegetation indices. 
I am interested in it because precipitation patterns are different region by region over the year. Therefore in my opinion, when comparing SPI with other indices for the growing season (March-September) or just to know whether there was any water scarcity starting from the rainfall period (e.g. October), it is better to calculate SPI-6 or above starting from October, not January.

**Comment by Nazira5** [comment]
I would like to know if it is possible not to put a limitation on ranges  of SPI or put at least -4 and 4 or above?

**Comment by monocongo** [comment]
Yes, it should be easily done. [Here](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/indices.py#L30) is most likely the only place you'll need to make changes, though [here](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/__spi__.py#L239) may also be necessary if using that script.

**Comment by Nazira5** [comment]
Thank you very much, but I am not a programmer, previously I was using ready steps and run this:

`spi --periodicity monthly --scales 1 2 3 6 9 12 24 36 48 60 72 --calibration_start_year 1981 --calibration_end_year 2020 --netcdf_precip PATH/file.nc --var_name_precip precip --output_file_base /PATH--multiprocessing all --save_params /PATH/file.nc --overwrite`
Therefore, I have no idea how to run the scripts you mentioned.

**Comment by Nazira5** [comment]
> This is not yet possible, it will be a feature request. When a calibration period is specified it is interpreted as January of the calibration start year through December of the calibration end year, inclusive.
> 
> If possible please provide further details about what you'd like to do. Is this something that others would benefit from or is it a niche use case? Is it for monthly or daily observations?

**Comment by Nazira5** [comment]
For my first question, I figured out, sorry for misleading and thank you very much. There is no need for another calibration start and end date, as we have different time scales (1, 3, 6, 9...) SPI values.

**Comment by monocongo** [comment]
I'm glad you were able to work out the details for that, and that what's provided here will be sufficient for your needs.

For the second issue, increasing the range from [-3.09, 3.09] to [-4, 4] see my comment above. It's literally a matter of changing the values in those files mentioned in the comment above. Bear in mind however that the range we've hard-coded has been determined to be the most scientifically valid, in that statistically it doesn't make sense to go beyond those bounds. I'm not a scientist or statistician so I can't say more than that, but if you want to go down that road then here's the way.

Good luck!

**Comment by Nazira5** [comment]
Thank you very much for your advice! Yes, it is no need to go beyond the values: -+3.09. Now, everything is clear, sorry for disturbing you.
