### ISSUE TITLE
TypeError: missing argument 'values'

### ISSUE THREAD

**Issue by wsor330** [monocongo/climate_indices#442]
**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

**Describe the bug**
```
Traceback (most recent call last):
  File "spi_monthly_test.py", line 79, in <module>
    periodicity=period)
```
Occurs when running script using indices functions, i.e. climate_indices.indices.spi(), with command line python via UNIX or WSL.
This error does not occur when using the same script on Spyder.

**To Reproduce**
Reproducible Code:
Data is from example input (excel file)
```
import pandas as pd
from climate_indices import indices, compute


def str2frame(estr, sep ='; |, ', lineterm = '\n', set_header = True):
    dat = [x.split() for x in estr.split(lineterm)][1:-1]
    cdf = pd.DataFrame(dat)
    if set_header:
        cdf = cdf.T.set_index(0, drop = True).T # flip, set ix, flip back
    return cdf

lats = 24.37
syear = 1985
eyear = 2017
scale_ci = 12

# rainfall dataset
rain = """
Year	JAN	FEB	MAR	APR	MAY	JUN	JULY	AUG	SEP	OCT	NOV	DEC
1985	0.0	8.0	25.1	20.5	22.5	27.3	10.8	15.0	16.8	10.4	0.0	0.0
1986	1.5	0.5	6.7	7.8	19.0	14.1	13.8	17.3	13.0	30.4	90.2	0.0
1987	0.0	0.0	11.0	21.4	17.8	21.8	14.0	21.4	13.2	24.3	21.4	0.6
1988	0.0	18.9	21.4	25.0	28.5	24.9	28.1	18.0	21.5	33.2	42.9	28.4
1989	0.0	1.8	0.0	32.4	12.8	15.4	22.4	20.2	19.8	21.9	8.0	0.0
1990	0.0	4.6	20.2	14.5	28.2	17.3	9.1	12.8	17.1	31.4	23.1	8.5
1991	0.0	0.0	4.9	28.0	30.2	15.0	9.2	18.1	9.3	21.1	64.0	27.0
1992	0.0	5.7	55.7	25.8	16.2	10.8	9.3	14.7	16.8	23.9	2.0	4.2
1993	9.0	10.4	10.8	21.7	40.9	28.9	29.0	17.2	20.3	10.6	5.3	0.0
1994	13.2	6.9	24.5	18.5	9.4	13.8	12.0	12.9	13.7	16.4	9.6	0.0
1995	2.0	8.6	21.3	9.6	19.4	28.4	9.9	17.7	13.9	16.9	13.1	0.0
1996	0.0	9.3	25.5	20.1	18.4	17.3	15.8	9.0	16.7	19.2	0.0	0.0
1997	0.0	7.4	13.5	13.6	17.3	18.4	20.7	15.2	19.7	6.7	9.1	8.0
1998	10.9	11.2	19.5	14.1	22.8	21.8	25.6	8.3	8.9	11.5	23.7	0.0
1999	0.0	0.0	21.2	8.1	29.6	10.7	11.9	18.6	11.9	10.9	31.4	0.0
2000	11.9	10.3	19.8	19.6	30.8	16.3	9.9	19.9	14.3	15.7	0.0	0.0
2001	0.0	21.6	12.9	12.4	17.4	24.7	13.3	12.3	16.4	21.2	9.3	0.0
2002	2.3	0.0	29.0	18.4	23.9	13.6	14.3	20.3	24.7	6.3	14.7	0.0
2003	1.2	3.4	5.2	19.5	36.0	23.6	13.7	11.6	15.2	6.5	0.0	45.3
2004	0.0	0.0	3.2	34.3	18.7	16.6	26.0	16.8	16.6	6.6	0.0	0.0
2005	0.0	95.0	11.0	6.1	22.2	7.5	16.8	5.3	7.7	6.9	0.0	0.0
2006	0.0	0.0	0.0	24.0	43.2	39.1	11.8	17.0	15.4	2.4	13.6	0.0
2007	0.0	14.2	26.6	26.4	25.2	36.2	17.1	23.0	22.5	15.4	19.2	0.0
2008	6.1	6.3	12.8	16.2	10.4	13.2	10.7	16.0	15.1	22.5	0.0	0.0
2009	0.0	4.2	8.8	18.2	21.4	14.0	12.3	17.1	20.6	14.2	0.0	0.0
2010	0.0	0.0	41.9	22.7	31.2	20.3	22.1	25.2	13.3	33.8	1.5	23.0
2011	10.1	3.8	17.4	12.8	31.8	17.8	13.8	15.1	15.8	30.8	0.0	0.0
2012	0.0	10.8	17.1	21.6	19.6	25.1	18.0	18.7	13.5	19.6	20.9	0.0
2013	0.0	0.0	1.6	15.7	36.3	27.7	21.4	26.1	11.7	17.9	0.0	0.0
2014	0.0	5.0	7.8	9.5	22.3	16.0	24.2	9.8	24.9	5.1	0.0	0.0
2015	0.0	15.5	1.6	29.4	23.5	20.8	13.8	17.6	16.8	17.8	11.6	42.6
2016	4.2	19.8	20.4	31.4	30.4	17.1	13.9	32.2	22.1	11.4	26.1	9.0
2017	0.0	5.2	18.3	28.7	32.5	32.9	11.5	30.3	14.6	24.7	1.4	28.9
"""
rain = str2frame(rain).iloc[:, 1:].astype(float)

date = pd.date_range('01-01-%s'%syear, '31-12-%s'%eyear, freq='M')
rain = pd.DataFrame(rain.values.flatten(), columns=['rainfall'], index=date).iloc[:, 0]


gamma = indices.Distribution.gamma
# period = compute.Periodicity.monthly
# gamma = 'gamma'
period = 'monthly'

spi = indices.spi(precips=rain.values, 
            scale=scale_ci, 
            distribution=gamma, 
            data_start_year=syear, 
            calibration_year_initial=syear, 
            calibration_year_final=eyear, 
            periodicity=period)
```

**Expected behavior**
To not have the shown error when running the script via UNIX or WSL, as in the case with running the script via Spyder

**Desktop (please complete the following information):**
- OS:  Windows
- Version:  10

- OS:  Linux
- Version:  HPC

**Comment by monocongo** [comment]
Please include more of the stack trace that you see when the error occurs. I have tried to include some meaningful error messages to help up describe issues like this when they occur, but we've not included enough of the error output to see them here.

One thing to try is to use Periodicity.monthly (the enumerated value) rather than the string "monthly" for the `period` variable in your example code. This confuses many users, I should switch from using an enumerated type to just a string for the period argument, it seems to be more intuitive for most users.

**Comment by wsor330** [comment]
Unfortunately that is all the error that is being provided. I will see if there is an option somehow to provide more.

I have used the enumerated value as shown above, but it is commented out because it seems it is an invalid argument. i.e.
```
    raise ValueError('Invalid periodicity argument: %s' % periodicity)

ValueError: Invalid periodicity argument: Periodicity.monthly
```

**Comment by monocongo** [comment]
Have you installed using the latest version from PyPI? I remember there were bugs like this in a previous release, and NOAA only stopped serving out-of-date versions of this package a few months ago, so it may be related to that? Make sure you're using the latest from the master branch or installing from PyPI.

**Comment by wsor330** [comment]
Oddly enough, I have version 1.0.0 from Spyder, which doesn't give me this problem. (This version came from anaconda.org)
However, for UNIX and WSL, version 1.0.9 is installed from the master branch and they both provide similar problems.

I'm thinking of downgrading to v1.0.0, but I'm assuming there are significantly more bugs? or am I wrong? 
I am specifically only using SPI and SPEI (monthly and daily data).

**Comment by wsor330** [comment]
Was trying out the different versions, and these three commits below were needed before the problem starts occurring.

1st commit is just to get the baseline package. 
2nd commit was needed it seems, before the 3rd commit can work (not sure why).
3rd commit is the latest version I can get to before the error starts occurring.

(1) way before v1.0.0 - may_15_2018
pip install git+https://github.com/monocongo/climate_indices.git@667013c9e66ba54444dbfd119e8fefed620a71eb
(2) checking before new version works - nov_14_2018
pip install git+https://github.com/monocongo/climate_indices.git@914fe85a6bb427f0fb3a064e9e6808258e1494c4
(3) checking newer version works -  mar_1_2019 - this is the latest version that works coupled with the two above
pip install git+https://github.com/monocongo/climate_indices.git@0fa4994acae7834a84639969697013c16d208e90

**Comment by wsor330** [comment]
Creating a new conda environment still provides similar problems (with 1.09 version from master branch).

**Comment by monocongo** [comment]
I'm sorry this repo is such a mess and that you're having these issues. I don't have much time to maintain this package lately and almost nobody contributes any fixes. If I get some time then I'd like to do some real housecleaning, and this kind of information will be helpful once I can get around to it. Thanks for your help!

If you will post a link to your input dataset then I will try to reproduce the error on my side and dive in with a debugger to see if I can work out what's going wrong for you.

**Comment by wsor330** [comment]
Thanks. I opted to just use the march 1 2019 v1.0 for now at-least.

The input dataset is just from the example_climate_indices. "Monthly_Seasonal_Data_Corrected_Version.xlsx". The values in string is provided in the original post as well.

**Comment by monocongo** [comment]
@wsor330 You might try starting with a fresh repository pull from the master branch. There should never be a need for all this contortion, nobody else has reported such a convoluted installation. On my local machine running Windows 10, I am seeing the expected results once I modified your example code as described below.

When I run the above code as-is I get the following error:

```
  File "C:/home/git/climate_indices/src/issue_442.py", line 65, in <module>
    spi = indices.spi(precips=rain.values,
TypeError: spi() got an unexpected keyword argument 'precips'
python-BaseException

Process finished with exit code 1
```

However, if I modify this code slightly by using the correct argument name (`values`) and the enumerated value for monthly data (`compute.Periodicity.monthly`) then everything runs as advertised:
```
import pandas as pd
from climate_indices import indices, compute


def str2frame(estr, sep ='; |, ', lineterm = '\n', set_header = True):
    dat = [x.split() for x in estr.split(lineterm)][1:-1]
    cdf = pd.DataFrame(dat)
    if set_header:
        cdf = cdf.T.set_index(0, drop = True).T # flip, set ix, flip back
    return cdf

lats = 24.37
syear = 1985
eyear = 2017
scale_ci = 12

# rainfall dataset
rain = """
Year	JAN	FEB	MAR	APR	MAY	JUN	JULY	AUG	SEP	OCT	NOV	DEC
1985	0.0	8.0	25.1	20.5	22.5	27.3	10.8	15.0	16.8	10.4	0.0	0.0
1986	1.5	0.5	6.7	7.8	19.0	14.1	13.8	17.3	13.0	30.4	90.2	0.0
1987	0.0	0.0	11.0	21.4	17.8	21.8	14.0	21.4	13.2	24.3	21.4	0.6
1988	0.0	18.9	21.4	25.0	28.5	24.9	28.1	18.0	21.5	33.2	42.9	28.4
1989	0.0	1.8	0.0	32.4	12.8	15.4	22.4	20.2	19.8	21.9	8.0	0.0
1990	0.0	4.6	20.2	14.5	28.2	17.3	9.1	12.8	17.1	31.4	23.1	8.5
1991	0.0	0.0	4.9	28.0	30.2	15.0	9.2	18.1	9.3	21.1	64.0	27.0
1992	0.0	5.7	55.7	25.8	16.2	10.8	9.3	14.7	16.8	23.9	2.0	4.2
1993	9.0	10.4	10.8	21.7	40.9	28.9	29.0	17.2	20.3	10.6	5.3	0.0
1994	13.2	6.9	24.5	18.5	9.4	13.8	12.0	12.9	13.7	16.4	9.6	0.0
1995	2.0	8.6	21.3	9.6	19.4	28.4	9.9	17.7	13.9	16.9	13.1	0.0
1996	0.0	9.3	25.5	20.1	18.4	17.3	15.8	9.0	16.7	19.2	0.0	0.0
1997	0.0	7.4	13.5	13.6	17.3	18.4	20.7	15.2	19.7	6.7	9.1	8.0
1998	10.9	11.2	19.5	14.1	22.8	21.8	25.6	8.3	8.9	11.5	23.7	0.0
1999	0.0	0.0	21.2	8.1	29.6	10.7	11.9	18.6	11.9	10.9	31.4	0.0
2000	11.9	10.3	19.8	19.6	30.8	16.3	9.9	19.9	14.3	15.7	0.0	0.0
2001	0.0	21.6	12.9	12.4	17.4	24.7	13.3	12.3	16.4	21.2	9.3	0.0
2002	2.3	0.0	29.0	18.4	23.9	13.6	14.3	20.3	24.7	6.3	14.7	0.0
2003	1.2	3.4	5.2	19.5	36.0	23.6	13.7	11.6	15.2	6.5	0.0	45.3
2004	0.0	0.0	3.2	34.3	18.7	16.6	26.0	16.8	16.6	6.6	0.0	0.0
2005	0.0	95.0	11.0	6.1	22.2	7.5	16.8	5.3	7.7	6.9	0.0	0.0
2006	0.0	0.0	0.0	24.0	43.2	39.1	11.8	17.0	15.4	2.4	13.6	0.0
2007	0.0	14.2	26.6	26.4	25.2	36.2	17.1	23.0	22.5	15.4	19.2	0.0
2008	6.1	6.3	12.8	16.2	10.4	13.2	10.7	16.0	15.1	22.5	0.0	0.0
2009	0.0	4.2	8.8	18.2	21.4	14.0	12.3	17.1	20.6	14.2	0.0	0.0
2010	0.0	0.0	41.9	22.7	31.2	20.3	22.1	25.2	13.3	33.8	1.5	23.0
2011	10.1	3.8	17.4	12.8	31.8	17.8	13.8	15.1	15.8	30.8	0.0	0.0
2012	0.0	10.8	17.1	21.6	19.6	25.1	18.0	18.7	13.5	19.6	20.9	0.0
2013	0.0	0.0	1.6	15.7	36.3	27.7	21.4	26.1	11.7	17.9	0.0	0.0
2014	0.0	5.0	7.8	9.5	22.3	16.0	24.2	9.8	24.9	5.1	0.0	0.0
2015	0.0	15.5	1.6	29.4	23.5	20.8	13.8	17.6	16.8	17.8	11.6	42.6
2016	4.2	19.8	20.4	31.4	30.4	17.1	13.9	32.2	22.1	11.4	26.1	9.0
2017	0.0	5.2	18.3	28.7	32.5	32.9	11.5	30.3	14.6	24.7	1.4	28.9
"""
rain = str2frame(rain).iloc[:, 1:].astype(float)

date = pd.date_range('01-01-%s'%syear, '31-12-%s'%eyear, freq='M')
rain = pd.DataFrame(rain.values.flatten(), columns=['rainfall'], index=date).iloc[:, 0]

spi = indices.spi(values=rain.values,
                  scale=scale_ci,
                  distribution=indices.Distribution.gamma,
                  data_start_year=syear,
                  calibration_year_initial=syear,
                  calibration_year_final=eyear,
                  periodicity=compute.Periodicity.monthly)
print(f'spi shape: {spi.shape}')
```
When I run the above I get the following result:
```
C:\Users\I29322\home\miniconda3\envs\climate\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.1\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 54761 --file C:/home/git/climate_indices/src/issue_442.py
Connected to pydev debugger (build 212.5080.64)
spi shape: (396,)

Process finished with exit code 0
```

**Comment by wsor330** [comment]
Thank you! I see the problem now. Sorry about this small problem.
I was initially working with the v1.0.0 and the argument name for the rainfall data is different compared to the new v1.0.9.
i.e. 'precips' vs 'values'
I see the Traceback error you got from the OP is slightly different, but points in the same direction. 

![Screenshot (204)](https://user-images.githubusercontent.com/43772253/133363611-0c970a2a-794a-42ed-b896-7073a5c2ae9d.png)
![Screenshot (205)](https://user-images.githubusercontent.com/43772253/133363613-8fa7e41a-97ce-46c2-8eea-677ea01407a3.png)
