### ISSUE TITLE
indices.spi and indices.spei expect differently named fitting params

### ISSUE THREAD

**Issue by WeatherGod** [monocongo/climate_indices#449]
`indices.spi()` and `indices.spei()` takes a dictionary of fitting params with differently named entries:

| SPI | SPEI |
| --- | ---- |
| alpha | alphas |
| beta | betas |
| prob_zero | probabilities_of_zero |
| loc | locs |
| scale | scales |
| skew | skews |

This makes it significantly more difficult to use `spi` and `spei` somewhat interchangeably (setting aside the fact that the latter takes two input variables...). I can normalize this, but it would technically be an API break. I was sort of wondering if instead we introduce a base class `FittingParams`, and have subclasses for each kind of distribution and pass that around. Then the functions can still accept dictionaries for backwards compatibility and also the FittingParams.

**Comment by monocongo** [comment]
I agree, the signatures should be in sync, somehow I've never noticed this. Your idea of using a FittingParams class to encapsulate is perfectly reasonable. But I'm not clear on how using a dictionary for backward compatibility would work, maybe via kwargs?

**Comment by WeatherGod** [comment]
Basic idea is that in the respective functions, there would be a `isinstance(fitting_params, dict)` check that, if true, would replace `fitting_params` with the appropriate subclass instance and the rest of the code would operate on the FittingParams instance. Using that approach, one could even go about setting a deprecation message when a dictionary is detected, moving users over.

**Comment by monocongo** [comment]
That should be fine, and the deprecation warning message upon dictionary detection is a next-level detail, nice one.
