### ISSUE TITLE
Lat "units" attribute required

### ISSUE THREAD

**Issue by heroldn** [monocongo/climate_indices#455]
Hi James et al., thanks for the great package. 

I'm trying to save the distribution parameters and get the following error which is due to the lat and lon coordinates not having the units attribute. In my netcdf file there are actually no coordinate variables for lat and lon (I know, not ideal) but I managed to calculate the SPI through this package without any dramas. (to confirm, there are lat and lon dimensions, but no corresponding coordinate variables).

**AttributeError: 'DataArray' object has no attribute 'units'**

Upon looking in the code it seems the units attribute for lat and lon is just required for some global metadata, [here](https://github.com/monocongo/climate_indices/blob/91108278507267046016d192a5b2fecf65ce69c4/src/climate_indices/__spi__.py#L462) and [here](https://github.com/monocongo/climate_indices/blob/91108278507267046016d192a5b2fecf65ce69c4/src/climate_indices/__spi__.py#L778). 

Can I confirm that it's fine to comment these out? I've done so and the package seems to be working fine but just would appreciate a sanity check from someone familiar with all this, before I compute a whole lot of data.

Thanks again.

**Comment by monocongo** [comment]
Yes, these lines can be commented out without causing catastrophe. Maybe we should add a check to make sure the units exist before assigning a non-existent value, which I assume is where the code falls over when those lines aren't commented out?

**Comment by heroldn** [comment]
Thanks for confirming. On the one hand a check would be nice, but unless you go all out to check for everything to prevent crashes like this I think it's ok to just expect users to have decent, CF compliant data. Just my opinion, but it forces everyone to get their house in order (or to modify the code!).
