### ISSUE TITLE
Create new version for PyPI update

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#456]
Bump the version on PyPI from 1.0.9 to 1.0.10

**Comment by liushuming75** [comment]
I am a new Linux player, I have downloaded the climate module, but why this error is reported, dear monocongo, can you help me?  
![image](https://user-images.githubusercontent.com/82938738/140552107-3282cc68-d8f1-4214-bbb7-a07391e1d6ab.png)

**Comment by liushuming75** [comment]
I have solved this problem by adding the Python path. Thank you very much for developing this module and providing a lot of convenience!

**Comment by monocongo** [comment]
@liushuming75 I'm glad you have worked out your issue. Thanks for the follow-up!

**Comment by monocongo** [comment]
This issue was resolved by #457
