### ISSUE TITLE
Addition of Precipitation Concentration Index

### ISSUE THREAD

**Issue by oshin94** [monocongo/climate_indices#459]
**Is your feature request related to a problem? Please describe.**
Precipitation Concentration Index or PCI  is an useful index to account the distribution of annual and seasonal rainfall amount. Even though the index itself is quite simple to implement it would be better to have a library which one may use when the need arises.

**Describe the solution you'd like**
I would like to contribute to this project by adding PCI as a function which was proposed by Oliver (1980) and further modified by De Luis et al. (2011) to give Seasonal PCI or SPCI.
Link for Oliver(1980): https://doi.org/10.1111/j.0033-0124.1980.00300.x
Link for De Luis et al. (2011): https://doi.org/10.5194/nhess-11-1259-2011

**Additional context**
Kindly let me know if this is in line with the aim of the project and if I may submit a PR.

**Comment by monocongo** [comment]
Yes, this will be very welcome. Thank you for your participation, @oshin94 !

Please bear in mind that I see my role as software engineering, and I am quite limited in my ability to vet the scientific/mathematic validity of the implementations. So please document these aspects as fully as possible, that'll be really helpful.

**Comment by oshin94** [comment]
> Yes, this will be very welcome. Thank you for your participation, @oshin94 !
> 
> Please bear in mind that I see my role as software engineering, and I am quite limited in my ability to vet the scientific/mathematic validity of the implementations. So please document these aspects as fully as possible, that'll be really helpful.

@monocongo Sure, I will make it a point to keep the references handy. I will be submitting a PR soon.
