### ISSUE TITLE
Update version number, upload new version to PyPI

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#461]
Now there is a new index, PCI so we should update the version in PyPI.

A short section about the PCI should be included in the README and/or docs as well but this can be more fully addressed in another issue. Maybe we'll instead (or at least) have release notes with this mentioned?

**Comment by Yassminaa** [comment]
How i can do this update?

**Comment by monocongo** [comment]
I need to do the actual upload to PyPI since I'm the package owner. Thanks for the kick in the pants, and my apologies for letting this languish.

If you'd like to help then maybe add a description of PCI to the list of available indices in the README.

**Comment by monocongo** [comment]
This will be resolved by an upcoming PR for #470
