### ISSUE TITLE
Doubt about netcdf format generated by the Climate Indices package

### ISSUE THREAD

**Issue by RR-Torres** [monocongo/climate_indices#463]
Dear colleagues,
I'm trying to calculate the SPI index through the python package made available by you at https://climate-indices.readthedocs.io/en/latest/.
I was able to perform all the necessary installations and processing described in the guide, but I am not able to open the netcdf file generated through CDO or Grads software. Would you kindly have an indication of how I should proceed?
Thanks in advance.
Regards,
Roger

**Comment by monocongo** [comment]
Thanks, Roger. Can you please post more details regarding your issue? Are you saying that the result files that are produced by this package are incompatible as input to CDO or Grads software? If so then please show the error messages and explain what you've done to go about fixing this so we can have a better idea ourselves on how to approach the issue.

**Comment by bennyistanto** [comment]
CDO required the variable should be in `time`, `lat`, `lon`, while the output from `climate-indices` in `lat`, `lon`, `time`, you can check this via `ncdump -h out.nc`

Let's re-order the variables into `time`,`lat`,`lon` using `ncpdq` command from NCO
```
ncpdq -a time,lat,lon in.nc out.nc
```

Then the output ready to open using CDO

**Comment by monocongo** [comment]
Closing for now since I'm pretty sure Benny's answer is the correct advice, but if any problems remain please re-open and describe errors with as much detail as possible. Thanks for your contribution/participation!
