### ISSUE TITLE
pip install climate_indices ...cd tests && pytest-3 outputs ============= 1 failed, 36 passed, 333 warnings in 488.50 seconds ==============

### ISSUE THREAD

**Issue by iajzenszmi** [monocongo/climate_indices#469]
pip install climate_indices ...cd tests && pytest-3 outputs ============= 1 failed, 36 passed, 333 warnings in 488.50 seconds ==============
![Screenshot from 2022-05-21 15-30-04](https://user-images.githubusercontent.com/5051767/169637079-cb1301a7-245a-4b74-9ac9-81ef0bab25fd.png)
**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: \[e.g. iOS]
- Version: \[e.g. 22]

**Additional context**

**Comment by monocongo** [comment]
Have you disabled `numba`'s just-in-time compilation? This is what's included in our `tox.ini` for that purpose:
```
NUMBA_DISABLE_JIT = 1
```
Please advise if that solves your issue. Thanks!

**Comment by monocongo** [comment]
This is almost certainly related to Numba's JIT not being disabled for the tests. If this issue persists after disabling that feature then please re-open this issue and show error details like before. Thanks for your contribution/participation, @iajzenszmi !
