### ISSUE TITLE
Is the unit of Available Water Capacity fixed for PDSI calculation?

### ISSUE THREAD

**Issue by levisocool** [monocongo/climate_indices#479]
My question is same as the title said. The unit of Available Water Capacity in example file "nclimgrid_lowres_soil.nc" is inches, and I am wondering if the unit should be converted into inches before using "Palmers monthly" climate index calculation?

**Comment by monocongo** [comment]
Save yourself some headaches and don't use the Palmers suite provided herein. Too many unresolved issues, not fully vetted by the team I was working with at NOAA when this code was developed. If someone can help develop this Palmers code then have at it, but don't use if for any kind of proper climate science/analysis/monitoring.

In any event, yes, the AWC unit does matter, Palmer used inches so we did too.
