### ISSUE TITLE
The influence of calibration period on scpdsi

### ISSUE THREAD

**Issue by Climatezhou** [monocongo/climate_indices#500]
When I change different calibration start(end) periods, the same scpdsi will get.

**Describe the bug**
I used the same gived precipitation, pet, and soil data in the examples, and different calibration periods. However, I get the same scpdsi.  Furthermore,  I chose the calibration start year smaller than data start year, the same result will get.  The red and blue lines show different calibration periods.

**To Reproduce**
process_climate_indices --index palmers --periodicity monthly --netcdf_precip /data/example/nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet /data/example/nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc /data/example/nclimgrid_lowres_soil.nc --var_name_awc awc --output_file_base /data/example/nclimgrid_check_1950-1979 --calibration_start_year 1950 --calibration_end_year 1979 --multiprocessing all

process_climate_indices --index palmers --periodicity monthly --netcdf_precip /data/example/nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet/data/example/nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc /data/example/nclimgrid_lowres_soil.nc --var_name_awc awc --output_file_base /data/example/nclimgrid_check_1896-1926 --calibration_start_year 1896 --calibration_end_year 1926 --multiprocessing all

process_climate_indices --index palmers --periodicity monthly --netcdf_precip /data/example/nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet/data/example/nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc /data/example/nclimgrid_lowres_soil.nc --var_name_awc awc --output_file_base /data/example/nclimgrid_check_1800-1900 --calibration_start_year 1800 --calibration_end_year 1900 --multiprocessing all

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/125747510/219909761-f9744c0f-412d-4d28-87b2-b19701674734.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by monocongo** [comment]
All the Palmers provided herein are experimental implementations (mentioned in the README), not intended for use in research. The idea is that these are provided as-is in case someone wants to finish the job. I left NOAA before completing work on this, and nobody else is interested in further developing it, so here we are. If you can find an open-source Python implementation of the Palmer indices then we'd like to see it and (if it's legit) replace what we have here with a wrapper on that code.
