### ISSUE TITLE
How to understand _FITTED_INDEX_VALID -3.09 and 3.09 ?

### ISSUE THREAD

**Issue by 1073766230** [monocongo/climate_indices#507]
Hey James,
 
 When I calculated spei, I met many values as -3.09 which were meand _FITTED_INDEX_VALID_ MIN in the package-climate_indices. My question is the cumulative probability of less than -3.09 should be about 0.1%  in the standard normal distribution,  but my calculations indicate a probability of up to 0.6% (see picture below). So should I consider -3.09 as nan and ignore it all, or how should I handle it? 

Here are the core parameter settings：

spei[:, row, col] = indices.spei(prec_monthly,
                                 pet_monthly,
                                 scale=3,
                                 distribution=indices.Distribution.pearson,  
                                 periodicity=compute.Periodicity.monthly,
                                 data_start_year=data_start_year,
                                 calibration_year_initial=data_start_year,
                                 calibration_year_final=calibration_year_final)

Here is the histgram：

![图片1](https://user-images.githubusercontent.com/95901919/229676573-f875a779-1500-4c64-8a16-a5c115606842.png)

Thank you very much！

**Comment by monocongo** [comment]
Just an idea: can you see if there is a comparable distribution in your precipitation data? I.e. do you have a lot of very small values that eventually compute to the minimum index value? We determined that -3.09 - 3.09 is the effective range but that was years ago, I'll have to do some looking to figure out why.

**Comment by 1073766230** [comment]
Hey James,

I'm very happy to hearing from you! Yeah, it's a good idea and I have checked the distribution in my precipation data as picture showed. It's true that many values locate in the range between 0.1~1 with the total probability of 11%.  But I don't understand why many small values could result in so many minimum -3.09. In other words, it can have many values being 0 at a dry area. If the above idea is true, the dry area should have many spei being -3.09, which I think is unbeliverable.

Here are Probability density distribution and cumulative probability density diagram respectively. 
![image](https://user-images.githubusercontent.com/95901919/230271595-669fd245-d9c2-429d-9a76-42742bb62b8a.png)
![image](https://user-images.githubusercontent.com/95901919/230272335-5b6595c7-6969-4683-8262-4004504ace55.png)

Also, I have another question. Should the distribution of spei be standard normal distribution? I have tried hard to use the R package "SPEI" to calculate spei, but the distribution isn't standard normal distribution unlike SPI is standard normal distribution. I would be grateful if you can help me this question.

Here is the spei calculated from R package"STI"
![image](https://user-images.githubusercontent.com/95901919/230275053-d7245df9-0256-44e6-8c0a-ab29367ee578.png)

Thank you very much!

**Comment by monocongo** [comment]
My apologies, I am comically undereducated about statistics for someone who maintains a package such as this, so I can only advise so far as to the underlying math. The indices computations don't fit values to a normal distribution but instead to gamma and Pearson-III distributions. That's about as deep as my understanding goes of the statistical underpinnings (I'm a programmer, not a scientist).

I'll close this ticket since it's not related to a bug or any other issues with the code. This might be a good topic to discuss in the [discussion section of this project](https://github.com/monocongo/climate_indices/discussions)?
