### ISSUE TITLE
Palmers Processing Time is more than 2 hours and still running

### ISSUE THREAD

**Issue by xeimyname1** [monocongo/climate_indices#516]
**Describe the bug**
Hi @monocongo, I am now trying to use your code for the derivation of Palmers Indices, however, code run time exceeds more than 2 hours. It is still running now so I am not sure how long will it take. 

**To Reproduce**
1. Inputs to the data are [Precipitation](https://studentutsedu-my.sharepoint.com/:u:/g/personal/shielo_n_muta_student_uts_edu_au/EbFWYPgoJkdKnO7dNO3OzbEB3dsBGX4D_UTjPkkaySlJWw?e=KN3kQk), [PET](https://studentutsedu-my.sharepoint.com/:u:/g/personal/shielo_n_muta_student_uts_edu_au/EeZh-lLPFm9Jr-THjKXHH2oBuudvizvstbijeHca34289w?e=tii24R) and [AWC](https://studentutsedu-my.sharepoint.com/:u:/g/personal/shielo_n_muta_student_uts_edu_au/EfzL66Z17FdAryj7YfkfK54BktX7BVTgnUhT7NN-TjL60w?e=zoiw8E) 
2. I just ran the code below
`process_climate_indices --index palmers --periodicity monthly --netcdf_precip ./precip_bom_ncpdq0.nc --var_name_precip ppt --netcdf_pet pet_bom_ncpdq0.nc --var_name_pet e0 --netcdf_awc ./awc_inches_units_remapped.nc --var_name_awc Band1 --output_file_base ./output/csiro --calibration_start_year 1980 --calibration_end_year 2020 --multiprocessing all`
3. The code had been running for 2 hours now. I am not sure if there is an error in my data. 

**Expected behavior**
I ran the code using the example you have given and it was successful, so I am expecting it will ran the same with my inputs. Precip and PET inputs ran well for SPI and SPEI

**Desktop (please complete the following information):**
I am using 
Apple M2 MacOS Ventura 13.3.2

Hopefully, you can give me feedback on this. Thank you so much

**Comment by xeimyname1** [comment]
Hi,

The process finally finished and I can confirm it is working. It took me 3 hours 27 minutes to run the code. Perhaps it will be faster if I utilize a machine with more cores. 

Thank you again.

**Comment by monocongo** [comment]
Thanks for following up @xeimyname1 !

Please be advised that the Palmers are experimental only and not vetted for use in proper research.

**Comment by xeimyname1** [comment]
Hi @monocongo ,

Yeah. I read the disclaimer. Thank you again for providing this.
