### ISSUE TITLE
SPI calculation is unsuccessful using climate_indices, while successful with SPEI package of R for same data

### ISSUE THREAD

**Issue by usmansall** [monocongo/climate_indices#548]
while running the climate_indices python package for processing of spi, there is always a error as below. I tried with various datasets and also run the calculation using SPEI package of R and it worked successfully with the same data. Can you please figure out what the problem is? Thanks in advance.

**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

**Describe the bug**

#########################################################################################
(climate-indices) D:\Python_Practice\climate_indices_drought\climate_indices-master>process_climate_indices --index spi --periodicity monthly --netcdf_precip D:/Python_Practice/climate_indices_drought/climate_indices-master/alina_precipitation_data.nc --var_name_precip ppt --output_file_base D:/Python_Practice/climate_indices_drought/climate_indices-master/results/IMERG --scales 12 --calibration_start_year 1994 --calibration_end_year 2023
2024-05-06  13:42:19 INFO Start time:    2024-05-06 13:42:19.556274
2024-05-06  13:42:19 INFO Computing 12-month SPI/Pearson
2024-05-06  13:42:19 ERROR Invalid dimensions for variable 'ppt': ('time', 'lat', 'lon')
2024-05-06  13:42:19 ERROR Failed to complete
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\climate_indices\__main__.py", line 1708, in main
    _compute_write_index(kwrgs)
  File "C:\Python312\Lib\site-packages\climate_indices\__main__.py", line 809, in _compute_write_index
    _drop_data_into_shared_arrays_grid(dataset,
  File "C:\Python312\Lib\site-packages\climate_indices\__main__.py", line 596, in _drop_data_into_shared_arrays_grid
    raise ValueError(message)
ValueError: Invalid dimensions for variable 'ppt': ('time', 'lat', 'lon')
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\process_climate_indices.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\climate_indices\__main__.py", line 1708, in main
    _compute_write_index(kwrgs)
  File "C:\Python312\Lib\site-packages\climate_indices\__main__.py", line 809, in _compute_write_index
    _drop_data_into_shared_arrays_grid(dataset,
  File "C:\Python312\Lib\site-packages\climate_indices\__main__.py", line 596, in _drop_data_into_shared_arrays_grid
    raise ValueError(message)
ValueError: Invalid dimensions for variable 'ppt': ('time', 'lat', 'lon')

##################################################################################################

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: \[e.g. iOS] win 64
- Version: \[e.g. 22]  windows 10

**Additional context**

**Comment by monocongo** [comment]
Thanks @usmansall 

Can you please post a link to the dataset `alina_precipitation_data.nc` used in the example above so I can attempt to replicate the issue?

**Comment by usmansall** [comment]
@monocongo Please download from here: https://we.tl/t-baNgrhCdtn 

Dear james, thanks for prompt reply. There are two datasets. (1) alina_precipitation_dataset.nc is working fine with SPEI code of R but does not work with climate_indices. However the other dataset (modified_dataset.nc) is not working with both, that hints about the data pre-processing issue, however you can also have a look once. Thanks a lot

**Comment by usmansall** [comment]
@monocongo could you please check the data and run the climate-indices package as I am still waiting to solve the issue. Many thanks and sorry for bothering. Please have data link again as first link could have been expired. https://we.tl/t-eOiu5XZm5n

**Comment by usmansall** [comment]
[SPI_Dataset_3.zip](https://github.com/monocongo/climate_indices/files/15416745/SPI_Dataset_3.zip)

Another dataset with same error message.

**Comment by usmansall** [comment]
> Thanks @usmansall
> 
> Can you please post a link to the dataset `alina_precipitation_data.nc` used in the example above so I can attempt to replicate the issue?

**Comment by monocongo** [comment]
Using the latest data you posted as input and using the latest branch from this repository I was able to produce SPI datasets without an error:
```
$ git clone https://github.com/monocongo/climate_indices.git
$ cd climate_indices/
$ poetry install
$ process_climate_indices --index spi --periodicity monthly --netcdf_precip ~/tmp/SPI_Dataset_3/modified_dataset.nc --var_name_precip precipitation --output_file_base ~/tmp/SPI_Dataset_3/results_IMERG --scales 12 --calibration_start_year 1994 --calibration_end_year 2023
2024-05-27  13:02:57 INFO Start time:    2024-05-27 13:02:57.975180
2024-05-27  13:02:58 INFO Computing 12-month SPI/Pearson
/home/james/git/climate_indices/src/climate_indices/compute.py:455: RuntimeWarning: divide by zero encountered in divide
  alpha = 4.0 / (skew * skew)
/home/james/git/climate_indices/src/climate_indices/compute.py:459: RuntimeWarning: invalid value encountered in multiply
  return loc - ((alpha * scale * skew) / 2.0)
2024-05-27  13:03:16 INFO Computing 12-month SPI/Gamma
2024-05-27  13:03:25 INFO End time:      2024-05-27 13:03:25.326466
2024-05-27  13:03:25 INFO Elapsed time:  0:00:27.351286
```

Please follow the approach outlined above and let me know if it still fails for you, including full error details.

**Comment by usmansall** [comment]
Dear James, thanks for your assistance and help. I cannot still run the code as it yields the following error message in any case:

ValueError: Invalid dimensions for variable 'ppt': ('time', 'lat', 'lon')

I am attaching here again the data, I am trying for running. Thanks in advance your input.

**Comment by monocongo** [comment]
I was able to reproduce the error. The issue is that we expect the data to use (lat, lon, time) as the dimension order, and this data had the time dimension as the first in that order rather than the last. I re-ordered the dimensions using [NCO](https://github.com/nco/nco) (NetCDF Operators) and that fixed the problem. Here's the NCO command I used for that:
```
ncpdq -a lat,lon,time ~/tmp/data_github/alina_precipitation_data.nc ~/tmp/data_github/reordered_alina_precipitation_data.nc
```
We used to have this cooked into our main processing script but it was problematic to maintain since the NCO package doesn't always work well on Windows and many of the users of this package run on Windows. But the onus is now on the user to get their data into the proper dimension order and that's not always obvious, as this example has demonstrated.

This highlights that the error message around this issue is insufficient for guiding users to a solution for the problem. We need to add better error handling around this issue so users can be informed of how to fix the problem. At a minimum, we need to add an error message indicating that the dimensions need to be (lat, lon, time) and in that exact order. We should also add a section to the README that describes how to wrangle the dataset so it'll be valid input to the main processing script.

**Comment by jamaa** [comment]
Is it not possible to reorder dimensions as needed using xarray? The following to me looks like it produces what is needed (using the example dataset from above):
```python
ds = xr.open_dataset("alina_precipitation_data.nc")
print(ds)
```

```
<xarray.Dataset> Size: 134MB
Dimensions:  (time: 360, lat: 241, lon: 193)
Coordinates:
  * time     (time) datetime64[ns] 3kB 1994-01-01 1994-02-01 ... 2023-12-01
  * lat      (lat) float64 2kB 13.98 13.94 13.9 13.85 ... 4.063 4.021 3.979
  * lon      (lon) float64 2kB -5.979 -5.938 -5.896 -5.854 ... 1.938 1.979 2.021
Data variables:
    ppt      (time, lat, lon) float64 134MB ...
```

```python
# maybe only one of the below lines is even enough?
ds2 = ds.transpose("lat", "lon", "time") # transpose the data variable's dimensions
ds2 = ds2[["lat", "lon", "time", "ppt"]] # select data in desired dimension order
print(ds2)
```

```
<xarray.Dataset> Size: 134MB
Dimensions:  (lat: 241, lon: 193, time: 360)
Coordinates:
  * lat      (lat) float64 2kB 13.98 13.94 13.9 13.85 ... 4.063 4.021 3.979
  * lon      (lon) float64 2kB -5.979 -5.938 -5.896 -5.854 ... 1.938 1.979 2.021
  * time     (time) datetime64[ns] 3kB 1994-01-01 1994-02-01 ... 2023-12-01
Data variables:
    ppt      (lat, lon, time) float64 134MB ...
```

If I'm not overlooking something, this could be easily built-in to climate_indices to allow for different dimension orders in the input?

**Comment by usmansall** [comment]
@monocongo many thanks for the hint. I will do so and in general 'nco' is great nausea using Windows as I tried it for another project.

@jamaa many thanks for your code and suggestion. I am a big fan of 'xarray' and will surely give it a try if it works for climate_indices. I imagine that netcdf data pre-processing a big sources of problem and source of error for the package implementation along with documentation issues as stated by James already.

**Comment by monocongo** [comment]
@jamaa this is a wonderful suggestion and looks to be an elegant solution to the problem. Thank you!
