### ISSUE TITLE
Configure for pip install

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#55]
https://packaging.python.org/tutorials/distributing-packages/#configuring-your-project

**Comment by kikocorreoso** [comment]
I'm working on this but first I'm checking all the hard dependencies and which ones could be replaced with other non third party options. 

@monocongo You could assign this to me if you want.

**Comment by monocongo** [comment]
Yes, will do (thanks for volunteering!), but I don't see how I can make the assignment, it's only allowing me to assign to myself, maybe I don't have your credentials as a contributor configured with sufficient permissions etc. for this?

**Comment by kikocorreoso** [comment]
Yes, I should be included in the repo as a maintainer to add me as assignee. But it is not necessary to do so if you are already aware that I'm working on it ;-)

**Comment by kikocorreoso** [comment]
See #64

**Comment by kikocorreoso** [comment]
I think this could be closed as #64 make the lib `pip` instalable.

**Comment by monocongo** [comment]
`python setup.py install` appears to work:

$ python setup.py install
running install
running bdist_egg
running egg_info
writing top-level names to indices_python.egg-info/top_level.txt
writing indices_python.egg-info/PKG-INFO
writing dependency_links to indices_python.egg-info/dependency_links.txt
writing requirements to indices_python.egg-info/requires.txt
reading manifest file 'indices_python.egg-info/SOURCES.txt'
writing manifest file 'indices_python.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/utils.py -> build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/pdinew.py -> build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/__init__.py -> build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/netcdf_utils.py -> build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/thornthwaite.py -> build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/compute.py -> build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/palmer.py -> build/bdist.linux-x86_64/egg/indices_python
copying build/lib/indices_python/indices.py -> build/bdist.linux-x86_64/egg/indices_python
byte-compiling build/bdist.linux-x86_64/egg/indices_python/utils.py to utils.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/indices_python/pdinew.py to pdinew.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/indices_python/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/indices_python/netcdf_utils.py to netcdf_utils.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/indices_python/thornthwaite.py to thornthwaite.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/indices_python/compute.py to compute.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/indices_python/palmer.py to palmer.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/indices_python/indices.py to indices.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying indices_python.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying indices_python.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying indices_python.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying indices_python.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying indices_python.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/indices_python-0.1.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing indices_python-0.1.0-py3.5.egg
Removing /home/james.adams/anaconda3/lib/python3.5/site-packages/indices_python-0.1.0-py3.5.egg
Copying indices_python-0.1.0-py3.5.egg to /home/james.adams/anaconda3/lib/python3.5/site-packages
indices-python 0.1.0 is already the active version in easy-install.pth

Installed /home/james.adams/anaconda3/lib/python3.5/site-packages/indices_python-0.1.0-py3.5.egg
Processing dependencies for indices-python==0.1.0
Searching for netCDF4==1.3.1
Best match: netCDF4 1.3.1
Adding netCDF4 1.3.1 to easy-install.pth file
Installing nc4tonc3 script to /home/james.adams/anaconda3/bin
Installing ncinfo script to /home/james.adams/anaconda3/bin
Installing nc3tonc4 script to /home/james.adams/anaconda3/bin

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for scipy==1.0.0
Best match: scipy 1.0.0
Adding scipy 1.0.0 to easy-install.pth file

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for pandas==0.21.0
Best match: pandas 0.21.0
Adding pandas 0.21.0 to easy-install.pth file

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for numba==0.35.0+10.g143f70e90
Best match: numba 0.35.0+10.g143f70e90
Adding numba 0.35.0+10.g143f70e90 to easy-install.pth file
Installing numba script to /home/james.adams/anaconda3/bin
Installing pycc script to /home/james.adams/anaconda3/bin

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for pytz==2016.2
Best match: pytz 2016.2
Adding pytz 2016.2 to easy-install.pth file

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for python-dateutil==2.5.1
Best match: python-dateutil 2.5.1
Adding python-dateutil 2.5.1 to easy-install.pth file

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for llvmlite==0.20.0
Best match: llvmlite 0.20.0
Adding llvmlite 0.20.0 to easy-install.pth file

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /home/james.adams/anaconda3/lib/python3.5/site-packages
Finished processing dependencies for indices-python==0.1.0
