### ISSUE TITLE
Error Cannot determine Numba type of <class 'logging.Logger'> when using 'indices.pet' function

### ISSUE THREAD

**Issue by DnyaneshWarade** [monocongo/climate_indices#551]
**Error Cannot determine Numba type of <class 'logging.Logger'> when using 'indices.pet' function**

**Describe the bug**
Getting error while using 'indices.pet' function
Error details:
Traceback (most recent call last):
  File "C:\MyWork\Personal\project\readNetCDF\calculateSPEI.py", line 28, in <module>
    pet = indices.pet(tmean, latitude, years.min())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyWork\Personal\project\readNetCDF\env\Lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\MyWork\Personal\project\readNetCDF\env\Lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: Literal propagation)
Failed in literal_propagation_subpipeline mode pipeline (step: performs partial type inference)
Untyped global name '_logger': Cannot determine Numba type of <class 'logging.Logger'>

File "env\Lib\site-packages\climate_indices\indices.py", line 586:
def pet(temperature_celsius: np.ndarray,
    <source elided>
               "90.0 inclusive)")
    _logger.error(message)
    ^

**To Reproduce**
1. Import the climate_indices package
2. try to use 'indices.pet' function by providing required parameters

**Expected behavior**
There should not be any error

**Desktop (please complete the following information):**
- OS: Windows
- Python Version: 3.12.3 
- Climate indices version: 1.0.12

**Comment by monocongo** [comment]
You are using an out-of-date version of the package. Please update from PyPI or the master branch of this repository and try again.

**Comment by DnyaneshWarade** [comment]
Yes this resolves the issue but during this I discovered that if user is using python version greater than 3.11 (like in my case 3.12) then the version of climate-indices installed is 1.0.12 and not the latest because for latest version of climate-indices max allowed python version is 3.11, so may be this needs to be handled in upcoming package releases.
