### ISSUE TITLE
repo reorganization

### ISSUE THREAD

**Issue by kikocorreoso** [monocongo/climate_indices#65]
The repository is a little bit messy right now.

Folders like *misc*, *notebooks*, *example_inputs* or *scripts* should be rethinked.

Do you want to provide examples of library usage? Try to organize *misc*, *notebooks*, *example_inputs* or *scripts* all in notebooks in the *notebooks* folder.

Do you have other plans for these folders? Just try to clarify about it and separate what is the library itself from what is documentation/examples, tests, ci,...

**Comment by monocongo** [comment]
You make a very good point. Things are how they are due to this being a catch-all repository for a long time for all indices related work I was doing, and now that it's being shared it needs to be trimmed to the essentials and the non-core code, examples, etc. can live elsewhere.

**Comment by monocongo** [comment]
notebooks - Jupyter notebooks demonstrating various aspects of the inner workings of the code for transparency and assistance with scientific validation
scripts - directory with scripts for ingest, processing, and comparison analysis
misc - one-off scripts only useful to James, may be handy later
example_inputs - data files useful for example scripts

**Comment by monocongo** [comment]
I will be happy to get most/all of these into notebooks if possible.  It was mentioned before that it's possible to load fixture data for tests from a database or some other data store, perhaps using an approach like this will make it possible to also eliminate the example_inputs/* files?

**Comment by kikocorreoso** [comment]
Datasets can be simple importable text/binary files within a `datasets` module, Check sklearn or statsmodels to see an example. As I don't know how you want to organize the code I can't figure out the best way to help here.

**Comment by monocongo** [comment]
We have much better organization of the project now, thanks again @kikocorreoso for providing the impetus for this.
