### ISSUE TITLE
Update .travis.yaml

### ISSUE THREAD

**Issue by kikocorreoso** [monocongo/climate_indices#68]
I think with the new changes in *setup.py* the following can be done:

* Remove *requirements.txt*
* Remove *environment.yaml*
* Update *.travis.yaml*. Instead of this:

```python
  # environment.yml contains the dependencies, for an environment named 'indices_python' 
  - conda env create -q -f environment.yml
  - source activate indices_python
  - python setup.py install

script: 
  # run all tests with coverage 
  - export NUMBA_DISABLE_JIT=1  # disable numba JIT
  - coverage run --source=indices_python -m unittest tests/test_*.py
```

use this:

```python
  - conda env create -n indices_python
  - source activate indices_python
  - pip install .

script: 
  # run all tests with coverage 
  - export NUMBA_DISABLE_JIT=1  # disable numba JIT
  - coverage run --source=indices_python setup.py test
```

I don't send a PR because maybe you will need some trial'n'error and maybe it is easier if you do direct commits to check if it is working.

**Comment by monocongo** [comment]
This sounds good to me, but I wonder if we cripple ourselves without an *environment.yml* file since it's necessary for creating a conda environment as described in the *README*. Or maybe there's a better way to provide this ability without requiring the presence of *environment.yml*?

**Comment by kikocorreoso** [comment]
with this:

`conda env create -n indices_python`

You are creating a conda environment so no need for the *environmental.yml* file.

Even better, you can create a condaenv for python 3.5 or for python 3.6 (or other versions) to test the library on different environments. This can be done in a mix of *environment.yml* and *.travis.yml* files or just using one of them (*.travis.yml*). The following on *travis.yml* will create two diferent conda envs with python 3.5/3.6:

`conda env create -n indices_python35 python=3.5`
`conda env create -n indices_python36 python=3.6`

So you can use both conda envs to test `indices_python` on both python versions.

Other useful thing you could do is to use [tox](https://tox.readthedocs.io/en/latest/) to test on several environments.

**Comment by monocongo** [comment]
It seems like there's something missing for the coverage module to be available for tests step, even though this is already included now in the tests_require section of setup.py

> 
> 0.17s$ coverage run --source=indices_python setup.py test
> coverage: command not found
> The command "coverage run --source=indices_python setup.py test" exited with 127.

**Comment by monocongo** [comment]
The Travis CI builds are working well now, this issue can/should probably be closed. Thanks again for your help, @kikocorreoso !
