### ISSUE TITLE
Publication with JORS?

### ISSUE THREAD

**Issue by DamienIrving** [monocongo/climate_indices#90]
I'm an associate editor with the [Journal of Open Research Software](https://openresearchsoftware.metajnl.com/) and just wanted to reach out to ask if you'd considered publishing a software article so that you can get academic credit (i.e. citations) for all the hard work involved in releasing and maintaining your software?

**Comment by monocongo** [comment]
Yes, I'm interested, however I'm afraid I don't have the budget.

**Comment by DamienIrving** [comment]
@monocongo Apologies for the delay in responding. 

Quoting directly from the [author guidelines](https://openresearchsoftware.metajnl.com/about/submissions/):
"You will be able to pay any amount from nothing to full charge, as we recognise that not all authors have access to funding, and we do not want fees to prevent the publication of worthy work"
